// This file is auto-generated by scripts/generate-icons.ts
// Do not edit manually.

import type { WrIcon } from '../types';

import { add } from './add';
import { addCircle } from './add-circle';
import { addCircleOutline } from './add-circle-outline';
import { alert } from './alert';
import { alertCircle } from './alert-circle';
import { alertCircleOutline } from './alert-circle-outline';
import { alertSquircle } from './alert-squircle';
import { arrowBack } from './arrow-back';
import { arrowBackCircle } from './arrow-back-circle';
import { arrowBottom } from './arrow-bottom';
import { arrowBottomCircle } from './arrow-bottom-circle';
import { arrowForward } from './arrow-forward';
import { arrowForwardCircle } from './arrow-forward-circle';
import { arrowTop } from './arrow-top';
import { arrowTopCircle } from './arrow-top-circle';
import { bug } from './bug';
import { bugOutline } from './bug-outline';
import { caretBack } from './caret-back';
import { caretBackCircle } from './caret-back-circle';
import { caretForward } from './caret-forward';
import { caretForwardCircle } from './caret-forward-circle';
import { checkmark } from './checkmark';
import { checkmarkCircle } from './checkmark-circle';
import { checkmarkCircleOutline } from './checkmark-circle-outline';
import { chevronDown } from './chevron-down';
import { chevronUp } from './chevron-up';
import { close } from './close';
import { closeCircle } from './close-circle';
import { closeCircleOutline } from './close-circle-outline';
import { cog } from './cog';
import { copy } from './copy';
import { copyOutline } from './copy-outline';
import { discover } from './discover';
import { document } from './document';
import { dotsHorizontal } from './dots-horizontal';
import { dotsVertical } from './dots-vertical';
import { download } from './download';
import { externalOutline } from './external-outline';
import { eye } from './eye';
import { eyeOff } from './eye-off';
import { fileAab } from './file-aab';
import { fileApk } from './file-apk';
import { fileApks } from './file-apks';
import { fileIpa } from './file-ipa';
import { fileZip } from './file-zip';
import { filter } from './filter';
import { filterOutline } from './filter-outline';
import { flash } from './flash';
import { folder } from './folder';
import { help } from './help';
import { home } from './home';
import { infoCircleOutline } from './info-circle-outline';
import { lock } from './lock';
import { lockOpened } from './lock-opened';
import { logoAndroid } from './logo-android';
import { logoAngular } from './logo-angular';
import { logoAppCenter } from './logo-app-center';
import { logoAppGallery } from './logo-app-gallery';
import { logoApple } from './logo-apple';
import { logoAppscreener } from './logo-appscreener';
import { logoAppstore } from './logo-appstore';
import { logoBankCenterCredit } from './logo-bank-center-credit';
import { logoChrome } from './logo-chrome';
import { logoDiscord } from './logo-discord';
import { logoFirebase } from './logo-firebase';
import { logoForteBank } from './logo-forte-bank';
import { logoGithub } from './logo-github';
import { logoGitlab } from './logo-gitlab';
import { logoGooglePlay } from './logo-google-play';
import { logoHalykBank } from './logo-halyk-bank';
import { logoInstagram } from './logo-instagram';
import { logoJusanBank } from './logo-jusan-bank';
import { logoKaspiBank } from './logo-kaspi-bank';
import { logoNpm } from './logo-npm';
import { logoOtbasyBank } from './logo-otbasy-bank';
import { logoOversecured } from './logo-oversecured';
import { logoRustore } from './logo-rustore';
import { logoStingray } from './logo-stingray';
import { logoTelegram } from './logo-telegram';
import { logoVk } from './logo-vk';
import { logoWhatsapp } from './logo-whatsapp';
import { logoYandexCloud } from './logo-yandex-cloud';
import { logoYandexTracker } from './logo-yandex-tracker';
import { modules } from './modules';
import { moon } from './moon';
import { play } from './play';
import { playBack } from './play-back';
import { playCircle } from './play-circle';
import { playForward } from './play-forward';
import { plusCircle } from './plus-circle';
import { reader } from './reader';
import { repeat } from './repeat';
import { search } from './search';
import { shield } from './shield';
import { shieldCheckmark } from './shield-checkmark';
import { shieldCheckmarkOutline } from './shield-checkmark-outline';
import { shieldOutline } from './shield-outline';
import { shuffle } from './shuffle';
import { stop } from './stop';
import { stopCircle } from './stop-circle';
import { sun } from './sun';
import { terminal } from './terminal';
import { time } from './time';
import { trash } from './trash';
import { user } from './user';
import { userAdd } from './user-add';
import { userCircle } from './user-circle';
import { userRemove } from './user-remove';
import { warning } from './warning';

export { add } from './add';
export { addCircle } from './add-circle';
export { addCircleOutline } from './add-circle-outline';
export { alert } from './alert';
export { alertCircle } from './alert-circle';
export { alertCircleOutline } from './alert-circle-outline';
export { alertSquircle } from './alert-squircle';
export { arrowBack } from './arrow-back';
export { arrowBackCircle } from './arrow-back-circle';
export { arrowBottom } from './arrow-bottom';
export { arrowBottomCircle } from './arrow-bottom-circle';
export { arrowForward } from './arrow-forward';
export { arrowForwardCircle } from './arrow-forward-circle';
export { arrowTop } from './arrow-top';
export { arrowTopCircle } from './arrow-top-circle';
export { bug } from './bug';
export { bugOutline } from './bug-outline';
export { caretBack } from './caret-back';
export { caretBackCircle } from './caret-back-circle';
export { caretForward } from './caret-forward';
export { caretForwardCircle } from './caret-forward-circle';
export { checkmark } from './checkmark';
export { checkmarkCircle } from './checkmark-circle';
export { checkmarkCircleOutline } from './checkmark-circle-outline';
export { chevronDown } from './chevron-down';
export { chevronUp } from './chevron-up';
export { close } from './close';
export { closeCircle } from './close-circle';
export { closeCircleOutline } from './close-circle-outline';
export { cog } from './cog';
export { copy } from './copy';
export { copyOutline } from './copy-outline';
export { discover } from './discover';
export { document } from './document';
export { dotsHorizontal } from './dots-horizontal';
export { dotsVertical } from './dots-vertical';
export { download } from './download';
export { externalOutline } from './external-outline';
export { eye } from './eye';
export { eyeOff } from './eye-off';
export { fileAab } from './file-aab';
export { fileApk } from './file-apk';
export { fileApks } from './file-apks';
export { fileIpa } from './file-ipa';
export { fileZip } from './file-zip';
export { filter } from './filter';
export { filterOutline } from './filter-outline';
export { flash } from './flash';
export { folder } from './folder';
export { help } from './help';
export { home } from './home';
export { infoCircleOutline } from './info-circle-outline';
export { lock } from './lock';
export { lockOpened } from './lock-opened';
export { logoAndroid } from './logo-android';
export { logoAngular } from './logo-angular';
export { logoAppCenter } from './logo-app-center';
export { logoAppGallery } from './logo-app-gallery';
export { logoApple } from './logo-apple';
export { logoAppscreener } from './logo-appscreener';
export { logoAppstore } from './logo-appstore';
export { logoBankCenterCredit } from './logo-bank-center-credit';
export { logoChrome } from './logo-chrome';
export { logoDiscord } from './logo-discord';
export { logoFirebase } from './logo-firebase';
export { logoForteBank } from './logo-forte-bank';
export { logoGithub } from './logo-github';
export { logoGitlab } from './logo-gitlab';
export { logoGooglePlay } from './logo-google-play';
export { logoHalykBank } from './logo-halyk-bank';
export { logoInstagram } from './logo-instagram';
export { logoJusanBank } from './logo-jusan-bank';
export { logoKaspiBank } from './logo-kaspi-bank';
export { logoNpm } from './logo-npm';
export { logoOtbasyBank } from './logo-otbasy-bank';
export { logoOversecured } from './logo-oversecured';
export { logoRustore } from './logo-rustore';
export { logoStingray } from './logo-stingray';
export { logoTelegram } from './logo-telegram';
export { logoVk } from './logo-vk';
export { logoWhatsapp } from './logo-whatsapp';
export { logoYandexCloud } from './logo-yandex-cloud';
export { logoYandexTracker } from './logo-yandex-tracker';
export { modules } from './modules';
export { moon } from './moon';
export { play } from './play';
export { playBack } from './play-back';
export { playCircle } from './play-circle';
export { playForward } from './play-forward';
export { plusCircle } from './plus-circle';
export { reader } from './reader';
export { repeat } from './repeat';
export { search } from './search';
export { shield } from './shield';
export { shieldCheckmark } from './shield-checkmark';
export { shieldCheckmarkOutline } from './shield-checkmark-outline';
export { shieldOutline } from './shield-outline';
export { shuffle } from './shuffle';
export { stop } from './stop';
export { stopCircle } from './stop-circle';
export { sun } from './sun';
export { terminal } from './terminal';
export { time } from './time';
export { trash } from './trash';
export { user } from './user';
export { userAdd } from './user-add';
export { userCircle } from './user-circle';
export { userRemove } from './user-remove';
export { warning } from './warning';

/**
 * Complete set of built-in icons.
 *
 * Importing this pulls every icon into the bundle — prefer importing
 * individual icons by name for tree-shaking. Use `wrIconSet` only for
 * icon pickers, documentation pages, or similar exhaustive listings.
 */
export const wrIconSet: WrIcon[] = [
  add,
  addCircle,
  addCircleOutline,
  alert,
  alertCircle,
  alertCircleOutline,
  alertSquircle,
  arrowBack,
  arrowBackCircle,
  arrowBottom,
  arrowBottomCircle,
  arrowForward,
  arrowForwardCircle,
  arrowTop,
  arrowTopCircle,
  bug,
  bugOutline,
  caretBack,
  caretBackCircle,
  caretForward,
  caretForwardCircle,
  checkmark,
  checkmarkCircle,
  checkmarkCircleOutline,
  chevronDown,
  chevronUp,
  close,
  closeCircle,
  closeCircleOutline,
  cog,
  copy,
  copyOutline,
  discover,
  document,
  dotsHorizontal,
  dotsVertical,
  download,
  externalOutline,
  eye,
  eyeOff,
  fileAab,
  fileApk,
  fileApks,
  fileIpa,
  fileZip,
  filter,
  filterOutline,
  flash,
  folder,
  help,
  home,
  infoCircleOutline,
  lock,
  lockOpened,
  logoAndroid,
  logoAngular,
  logoAppCenter,
  logoAppGallery,
  logoApple,
  logoAppscreener,
  logoAppstore,
  logoBankCenterCredit,
  logoChrome,
  logoDiscord,
  logoFirebase,
  logoForteBank,
  logoGithub,
  logoGitlab,
  logoGooglePlay,
  logoHalykBank,
  logoInstagram,
  logoJusanBank,
  logoKaspiBank,
  logoNpm,
  logoOtbasyBank,
  logoOversecured,
  logoRustore,
  logoStingray,
  logoTelegram,
  logoVk,
  logoWhatsapp,
  logoYandexCloud,
  logoYandexTracker,
  modules,
  moon,
  play,
  playBack,
  playCircle,
  playForward,
  plusCircle,
  reader,
  repeat,
  search,
  shield,
  shieldCheckmark,
  shieldCheckmarkOutline,
  shieldOutline,
  shuffle,
  stop,
  stopCircle,
  sun,
  terminal,
  time,
  trash,
  user,
  userAdd,
  userCircle,
  userRemove,
  warning,
];
