/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

import { type Rule, type SchematicContext, SchematicsException, type Tree } from '@angular-devkit/schematics';
import { getWorkspace } from '@schematics/angular/utility/workspace';

import type { Schema } from './schema';

/**
 * Curated common icon sets. Identifiers match `ngwr/icon` exports — kept
 * short on purpose so the generated file stays readable.
 */
const SETS: Record<NonNullable<Schema['set']>, readonly string[]> = {
  basic: ['checkmark', 'close', 'add', 'edit', 'trash', 'search', 'copy'],
  navigation: [
    'chevronDown',
    'chevronLeft',
    'chevronRight',
    'chevronUp',
    'arrowBack',
    'arrowForward',
    'arrowTop',
    'arrowBottom',
    'menu',
    'dotsHorizontal',
    'dotsVertical',
  ],
  forms: ['eye', 'eyeOff', 'lock', 'lockOpened', 'calendar', 'time', 'filter', 'checkmark', 'close'],
  feedback: ['alert', 'alertCircle', 'infoCircleOutline', 'checkmarkCircle', 'closeCircle', 'warning', 'bell'],
};

/** Default fallback when neither `set` nor `icons` is supplied. */
const DEFAULT_SET: NonNullable<Schema['set']> = 'basic';

function iconSet(options: Schema): Rule {
  return async (tree: Tree, context: SchematicContext) => {
    const workspace = await getWorkspace(tree);
    const projectName = options.project ?? (workspace.extensions.defaultProject as string | undefined);
    const project = (projectName && workspace.projects.get(projectName)) ?? workspace.projects.values().next().value;

    if (!project) {
      throw new SchematicsException('ngwr:icon-set: no Angular project found.');
    }

    const sourceRoot = project.sourceRoot ?? `${project.root || ''}/src`.replace(/^\//, '');
    const dirPath = options.path ?? `${sourceRoot}/app`;
    const fileName = (options.name ?? 'icons').replace(/\.ts$/, '');
    const filePath = `${dirPath}/${fileName}.ts`;

    // Build the deduped icon list — set + explicit icons, or default fallback.
    const fromSet = options.set ? (SETS[options.set] ?? []) : [];
    const fromList = options.icons
      ? options.icons
          .split(',')
          .map(s => s.trim())
          .filter(Boolean)
      : [];

    const icons = unique([...fromSet, ...fromList]);
    if (icons.length === 0) icons.push(...SETS[DEFAULT_SET]);

    if (tree.exists(filePath)) {
      context.logger.warn(
        `ngwr: ${filePath} already exists — skipping. Pass --name to write a different file, or delete it first.`
      );
      return tree;
    }

    const exportName = options.exportName ?? 'APP_ICONS';
    const importList = icons.join(', ');
    const arrayList = icons.join(', ');

    tree.create(filePath, renderFile(importList, exportName, arrayList));
    context.logger.info(`✓ Created ${filePath} with ${icons.length} icons.`);
    context.logger.info(printWiringHint(fileName, exportName));

    return tree;
  };
}

function renderFile(importList: string, exportName: string, arrayList: string): string {
  return `/**
 * Tree-shaken ngwr icon set. Generated by \`ng g ngwr:icon-set\`.
 * Edit freely — re-running with --name=<other> writes a separate file.
 */
import { ${importList} } from 'ngwr/icon';

export const ${exportName} = [${arrayList}] as const;
`;
}

function printWiringHint(fileName: string, exportName: string): string {
  return `
Next step — wire the set into bootstrap:

  import { provideWrIcons } from 'ngwr/icon';
  import { ${exportName} } from './${fileName}';

  bootstrapApplication(AppComponent, {
    providers: [provideWrIcons(${exportName})],
  });
`;
}

function unique<T>(list: readonly T[]): T[] {
  return Array.from(new Set(list));
}

export default iconSet;
