import type { Routes } from '@angular/router';

export const routes = {
  index: '/',
  docs: {
    index: 'docs',
    gettingStarted: {
      index: 'getting-started',
      installation: 'installation',
    },
    components: {
      index: 'components',
      alert: 'alert',
      autocomplete: 'autocomplete',
      avatar: 'avatar',
      badge: 'badge',
      breadcrumbs: 'breadcrumbs',
      button: 'button',
      buttonGroup: 'button-group',
      calendar: 'calendar',
      checkbox: 'checkbox',
      checkboxGroup: 'checkbox-group',
      collapse: 'collapse',
      colorPicker: 'color-picker',
      datePicker: 'date-picker',
      dateTimePicker: 'date-time-picker',
      dialog: 'dialog',
      divider: 'divider',
      drawer: 'drawer',
      form: 'form',
      icon: 'icon',
      input: 'input',
      inputNumber: 'input-number',
      inputOtp: 'input-otp',
      popconfirm: 'popconfirm',
      popover: 'popover',
      progress: 'progress',
      qrCode: 'qrcode',
      radio: 'radio',
      radioGroup: 'radio-group',
      segmented: 'segmented',
      skeleton: 'skeleton',
      slider: 'slider',
      spinner: 'spinner',
      switch: 'switch',
      tag: 'tag',
      tabs: 'tabs',
      textarea: 'textarea',
      timePicker: 'time-picker',
      toast: 'toast',
      tooltip: 'tooltip',
      select: 'select',
      dropdown: 'dropdown',
      pagination: 'pagination',
      table: 'table',
      window: 'window',
    },
    core: {
      index: 'core',
      colors: 'color',
      grid: 'grid',
      overlay: 'overlay',
      utils: 'utils',
    },
  },
};

export const routing: Routes = [
  {
    path: '',
    loadComponent: () => import('#shell'),
    children: [
      {
        path: '',
        pathMatch: 'full',
        loadComponent: () => import('./home/home.component'),
      },
      {
        path: routes.docs.index,
        loadChildren: () => import('./docs/docs.routing'),
      },
    ],
  },
];
