import type { Routes } from '@angular/router';

import {
  ANIMATIONS_SIDEBAR,
  COMPONENTS_SIDEBAR,
  DIRECTIVES_SIDEBAR,
  GETTING_STARTED_SIDEBAR,
  ICONS_SIDEBAR,
  PIPES_SIDEBAR,
  SERVICES_SIDEBAR,
  TRANSLATE_SIDEBAR,
  TYPOGRAPHY_SIDEBAR,
  TOKENS_SIDEBAR,
  INTERFACES_SIDEBAR,
  UTILS_SIDEBAR,
  VALIDATORS_SIDEBAR,
} from './_layout/sidebar/configs';

export const routes = {
  index: '/',
  icons: {
    index: 'icons',
    overview: 'overview',
    lucide: 'lucide',
    feather: 'feather',
    tabler: 'tabler',
    phosphor: 'phosphor',
    heroicons: 'heroicons',
    iconoir: 'iconoir',
    radix: 'radix',
    bootstrap: 'bootstrap',
  },
  gettingStarted: {
    index: 'getting-started',
    installation: 'installation',
    theming: 'theming',
    color: 'color',
    grid: 'grid',
    overlay: 'overlay',
    mobile: 'mobile',
    i18n: 'i18n',
    configuration: 'configuration',
    schematics: 'schematics',
  },
  tokens: {
    index: 'tokens',
    colors: 'colors',
    sizing: 'sizing',
    typography: 'typography',
    density: 'density',
  },
  components: {
    index: 'components',
    alert: 'alert',
    anchor: 'anchor',
    avatar: 'avatar',
    charts: 'charts',
    sparkline: 'sparkline',
    gauge: 'gauge',
    barChart: 'bar-chart',
    donutChart: 'donut-chart',
    lineChart: 'line-chart',
    calendarHeatmap: 'calendar-heatmap',
    squircle: 'squircle',
    backTop: 'back-top',
    badge: 'badge',
    breadcrumbs: 'breadcrumbs',
    burger: 'burger',
    button: 'button',
    buttonGroup: 'button-group',
    calendar: 'calendar',
    card: 'card',
    carousel: 'carousel',
    cascader: 'cascader',
    checkbox: 'checkbox',
    collapse: 'collapse',
    colorPicker: 'color-picker',
    commandPalette: 'command-palette',
    compare: 'compare',
    contextMenu: 'context-menu',
    counter: 'counter',
    datePicker: 'date-picker',
    dialog: 'dialog',
    divider: 'divider',
    drawer: 'drawer',
    empty: 'empty',
    form: 'form',
    formField: 'form-field',
    icon: 'icon',
    lightbox: 'lightbox',
    imageCropper: 'image-cropper',
    input: 'input',
    inputNumber: 'input-number',
    layout: 'layout',
    list: 'list',
    inputOtp: 'input-otp',
    keyboard: 'keyboard',
    knob: 'knob',
    mention: 'mention',
    meterGroup: 'meter-group',
    pageHeader: 'page-header',
    result: 'result',
    speedDial: 'speed-dial',
    splitter: 'splitter',
    statistic: 'statistic',
    timeline: 'timeline',
    toolbar: 'toolbar',
    descriptions: 'descriptions',
    popconfirm: 'popconfirm',
    popover: 'popover',
    progress: 'progress',
    qrCode: 'qrcode',
    radio: 'radio',
    rating: 'rating',
    segmented: 'segmented',
    skeleton: 'skeleton',
    slider: 'slider',
    spinner: 'spinner',
    stepper: 'stepper',
    switch: 'switch',
    tabs: 'tabs',
    typography: 'typography',
    textarea: 'textarea',
    toast: 'toast',
    tree: 'tree',
    select: 'select',
    sidebar: 'sidebar',
    dropdown: 'dropdown',
    fileUpload: 'file-upload',
    pagination: 'pagination',
    table: 'table',
    virtualScroll: 'virtual-scroll',
    dragDrop: 'drag-drop',
    window: 'window',
  },
  directives: {
    index: 'directives',
    affix: 'affix',
    autofocus: 'autofocus',
    autosize: 'autosize',
    clickOutside: 'click-outside',
    copyToClipboard: 'copy-to-clipboard',
  },
  // Visual effects + animations. Mixed bag of in-house components and
  // ports of reactbits.dev effects (attribution in each file).
  animations: {
    index: 'animations',
    borderGlow: 'border-glow',
    aurora: 'aurora',
    marquee: 'marquee',
    confetti: 'confetti',
    // Reactbits ports (built in follow-up commits)
    spotlightCard: 'spotlight-card',
    tiltCard: 'tilt-card',
    clickSpark: 'click-spark',
    waves: 'waves',
    starBorder: 'star-border',
    splashCursor: 'splash-cursor',
    splitText: 'split-text',
    blurText: 'blur-text',
    shinyText: 'shiny-text',
    gradientText: 'gradient-text',
    rotatingText: 'rotating-text',
    typewriter: 'typewriter',
    decryptText: 'decrypt-text',
    glitchText: 'glitch-text',
    fuzzyText: 'fuzzy-text',
    fallingText: 'falling-text',
    circularText: 'circular-text',
  },
  pipes: {
    index: 'pipes',
    wrNumber: 'wr-number',
    wrBytes: 'wr-bytes',
    wrDate: 'wr-date',
    wrTruncate: 'wr-truncate',
    wrMark: 'wr-mark',
    wrPlural: 'wr-plural',
    range: 'range',
  },
  services: {
    index: 'services',
    theme: 'theme',
    scroll: 'scroll',
    hotkey: 'hotkey',
    media: 'media',
    platform: 'platform',
    meta: 'meta',
    storage: 'storage',
    i18n: 'i18n',
    density: 'density',
    clipboard: 'clipboard',
    cookie: 'cookie',
    loadingBar: 'loading-bar',
  },
  utils: {
    index: 'utils',
    types: 'types',
    // Math
    clamp: 'clamp',
    round: 'round',
    numAttr: 'num-attr',
    // Css helpers
    resolveCssSize: 'resolve-css-size',
    getRootFontSize: 'get-root-font-size',
    // Ids
    randomId: 'random-id',
    // Type guards
    isDefined: 'is-defined',
    isNonEmptyArray: 'is-non-empty-array',
    isObservable: 'is-observable',
    // Keyboard
    keys: 'keys',
    hasModifier: 'has-modifier',
    isPrintableKey: 'is-printable-key',
    // Functional primitives
    noop: 'noop',
    badgeLog: 'badge-log',
    debounce: 'debounce',
    throttle: 'throttle',
    // Focus
    getFocusableElements: 'get-focusable-elements',
    trapFocus: 'trap-focus',
  },
  typography: {
    index: 'typography',
    overview: 'overview',
    headings: 'headings',
    paragraphs: 'paragraphs',
    lists: 'lists',
    links: 'links',
    text: 'text',
    code: 'code',
    keyboard: 'keyboard',
  },
  translate: {
    index: 'translate',
    overview: 'overview',
    setup: 'setup',
    usage: 'usage',
    scopes: 'scopes',
    interpolation: 'interpolation',
    api: 'api',
  },
  interfaces: {
    index: 'interfaces',
    overview: 'overview',
    common: 'common',
    theme: 'theme',
    catalog: 'catalog',
  },
  validators: {
    index: 'validators',
    noWhitespace: 'no-whitespace',
    hexColor: 'hex-color',
    url: 'url',
    cardNumber: 'card-number',
    cvc: 'cvc',
    iban: 'iban',
    match: 'match',
    oneOf: 'one-of',
    minDate: 'min-date',
    maxDate: 'max-date',
  },
};

export const routing: Routes = [
  {
    path: '',
    loadComponent: () => import('./home/home'),
  },
  {
    path: '',
    loadComponent: () => import('#layout'),
    children: [
      {
        path: routes.gettingStarted.index,
        data: { sidebar: GETTING_STARTED_SIDEBAR },
        loadChildren: () => import('./getting-started/getting-started.routing'),
      },
      {
        path: routes.tokens.index,
        data: { sidebar: TOKENS_SIDEBAR },
        loadChildren: () => import('./tokens/tokens.routing'),
      },
      {
        path: routes.components.index,
        data: { sidebar: COMPONENTS_SIDEBAR },
        loadChildren: () => import('./components/components.routing'),
      },
      {
        path: routes.icons.index,
        data: { sidebar: ICONS_SIDEBAR },
        loadChildren: () => import('./icons/icons.routing'),
      },
      {
        path: routes.directives.index,
        data: { sidebar: DIRECTIVES_SIDEBAR },
        loadChildren: () => import('./directives/directives.routing'),
      },
      {
        path: routes.animations.index,
        data: { sidebar: ANIMATIONS_SIDEBAR },
        loadChildren: () => import('./animations/animations.routing'),
      },
      {
        path: routes.pipes.index,
        data: { sidebar: PIPES_SIDEBAR },
        loadChildren: () => import('./pipes/pipes.routing'),
      },
      {
        path: routes.services.index,
        data: { sidebar: SERVICES_SIDEBAR },
        loadChildren: () => import('./services/services.routing'),
      },
      {
        path: routes.utils.index,
        data: { sidebar: UTILS_SIDEBAR },
        loadChildren: () => import('./utils/utils.routing'),
      },
      {
        path: routes.interfaces.index,
        data: { sidebar: INTERFACES_SIDEBAR },
        loadChildren: () => import('./interfaces/interfaces.routing'),
      },
      // The section briefly shipped as /types — keep those URLs alive.
      { path: 'types/:page', redirectTo: 'interfaces/:page' },
      { path: 'types', redirectTo: 'interfaces' },
      {
        path: routes.typography.index,
        data: { sidebar: TYPOGRAPHY_SIDEBAR },
        loadChildren: () => import('./typography/typography.routing'),
      },
      {
        path: routes.translate.index,
        data: { sidebar: TRANSLATE_SIDEBAR },
        loadChildren: () => import('./translate/translate.routing'),
      },
      {
        path: routes.validators.index,
        data: { sidebar: VALIDATORS_SIDEBAR },
        loadChildren: () => import('./validators/validators.routing'),
      },
    ],
  },
];
