import type { Routes } from '@angular/router';

import {
  COMPONENTS_SIDEBAR,
  DIRECTIVES_SIDEBAR,
  GETTING_STARTED_SIDEBAR,
  PIPES_SIDEBAR,
  SERVICES_SIDEBAR,
  UTILS_SIDEBAR,
} from './_layout/sidebar/configs';

export const routes = {
  index: '/',
  gettingStarted: {
    index: 'getting-started',
    installation: 'installation',
    color: 'color',
    grid: 'grid',
    overlay: 'overlay',
  },
  components: {
    index: 'components',
    alert: 'alert',
    anchor: 'anchor',
    animatedText: 'animated-text',
    aurora: 'aurora',
    autocomplete: 'autocomplete',
    avatar: 'avatar',
    confetti: 'confetti',
    countUp: 'count-up',
    marquee: 'marquee',
    motion: 'motion',
    charts: 'charts',
    squircle: 'squircle',
    backTop: 'back-top',
    badge: 'badge',
    button: 'button',
    buttonGroup: 'button-group',
    calendar: 'calendar',
    carousel: 'carousel',
    checkbox: 'checkbox',
    checkboxGroup: 'checkbox-group',
    collapse: 'collapse',
    colorPicker: 'color-picker',
    compare: 'compare',
    contextMenu: 'context-menu',
    counter: 'counter',
    datePicker: 'date-picker',
    dateTimePicker: 'date-time-picker',
    dialog: 'dialog',
    divider: 'divider',
    drawer: 'drawer',
    empty: 'empty',
    form: 'form',
    icon: 'icon',
    imageCropper: 'image-cropper',
    input: 'input',
    inputNumber: 'input-number',
    layout: 'layout',
    inputOtp: 'input-otp',
    keyboard: 'keyboard',
    knob: 'knob',
    mention: 'mention',
    meterGroup: 'meter-group',
    pageHeader: 'page-header',
    result: 'result',
    speedDial: 'speed-dial',
    splitter: 'splitter',
    statistic: 'statistic',
    timeline: 'timeline',
    toolbar: 'toolbar',
    descriptions: 'descriptions',
    popconfirm: 'popconfirm',
    popover: 'popover',
    progress: 'progress',
    qrCode: 'qrcode',
    radio: 'radio',
    radioGroup: 'radio-group',
    rating: 'rating',
    segmented: 'segmented',
    skeleton: 'skeleton',
    slider: 'slider',
    spinner: 'spinner',
    stepper: 'stepper',
    switch: 'switch',
    tag: 'tag',
    tabs: 'tabs',
    typography: 'typography',
    textarea: 'textarea',
    timePicker: 'time-picker',
    toast: 'toast',
    tooltip: 'tooltip',
    tree: 'tree',
    select: 'select',
    dropdown: 'dropdown',
    fileUpload: 'file-upload',
    pagination: 'pagination',
    table: 'table',
    window: 'window',
  },
  directives: {
    index: 'directives',
    // Filled in by Phase 2 (split into per-directive pages).
    autofocus: 'autofocus',
    autosize: 'autosize',
    borderGlow: 'border-glow',
    clickOutside: 'click-outside',
    copyToClipboard: 'copy-to-clipboard',
    reveal: 'reveal',
    shimmer: 'shimmer',
    spotlight: 'spotlight',
    tilt: 'tilt',
  },
  pipes: {
    index: 'pipes',
    wrNumber: 'wr-number',
    wrBytes: 'wr-bytes',
    wrDate: 'wr-date',
    wrTruncate: 'wr-truncate',
    range: 'range',
  },
  services: {
    index: 'services',
    theme: 'theme',
    scroll: 'scroll',
    hotkey: 'hotkey',
    media: 'media',
    platform: 'platform',
    meta: 'meta',
  },
  utils: {
    index: 'utils',
    cssSize: 'css-size',
    randomId: 'random-id',
    guards: 'guards',
    keys: 'keys',
    noop: 'noop',
    badgeLog: 'badge-log',
    rate: 'rate',
    focus: 'focus',
  },
};

export const routing: Routes = [
  {
    path: '',
    loadComponent: () => import('./home/home'),
  },
  {
    path: '',
    loadComponent: () => import('#layout'),
    children: [
      {
        path: routes.gettingStarted.index,
        data: { sidebar: GETTING_STARTED_SIDEBAR },
        loadChildren: () => import('./getting-started/getting-started.routing'),
      },
      {
        path: routes.components.index,
        data: { sidebar: COMPONENTS_SIDEBAR },
        loadChildren: () => import('./components/components.routing'),
      },
      {
        path: routes.directives.index,
        data: { sidebar: DIRECTIVES_SIDEBAR },
        loadChildren: () => import('./directives/directives.routing'),
      },
      {
        path: routes.pipes.index,
        data: { sidebar: PIPES_SIDEBAR },
        loadChildren: () => import('./pipes/pipes.routing'),
      },
      {
        path: routes.services.index,
        data: { sidebar: SERVICES_SIDEBAR },
        loadChildren: () => import('./services/services.routing'),
      },
      {
        path: routes.utils.index,
        data: { sidebar: UTILS_SIDEBAR },
        loadChildren: () => import('./utils/utils.routing'),
      },
    ],
  },
];
