/**
 * Every URL segment the site uses, in one place.
 *
 * Imported as `#routing` by the Angular route tree, by every sidebar
 * config and by the build scripts that walk the site — so a slug is
 * written once and a rename is a compile error rather than a dead link.
 */
export const routes = {
  index: '/',
  icons: {
    index: 'icons',
    overview: 'overview',
    lucide: 'lucide',
    feather: 'feather',
    tabler: 'tabler',
    phosphor: 'phosphor',
    heroicons: 'heroicons',
    iconoir: 'iconoir',
    radix: 'radix',
    bootstrap: 'bootstrap',
  },
  /** Getting the library into an app. Not how to use a subsystem — that's `guides`. */
  docs: {
    index: 'docs',
    introduction: 'introduction',
    installation: 'installation',
    configuration: 'configuration',
    migration: 'migration',
    skills: 'skills',
    mcp: 'mcp-server',
  },
  /** The chart components, their own cluster rather than a group under `reference`. */
  charts: {
    index: 'charts',
    barChart: 'bar-chart',
    calendarHeatmap: 'calendar-heatmap',
    donutChart: 'donut-chart',
    gauge: 'gauge',
    lineChart: 'line-chart',
    meterGroup: 'meter-group',
    sparkline: 'sparkline',
  },
  /** Task-oriented walkthroughs that span several APIs and link into `reference`. */
  guides: {
    index: 'guides',
    theming: 'theming',
    color: 'color',
    grid: 'grid',
    forms: 'forms',
    overlay: 'overlay',
    mobile: 'mobile',
    keyboard: 'keyboard',
    ssr: 'ssr',
    testing: 'testing',
    mcp: 'mcp',
    agentSkill: 'agent-skill',
    csp: 'csp',
    tokens: 'tokens',
    translations: 'translations',
    typography: 'typography',
  },
  /** One public API per page: description, demos, and the full API table. */
  reference: {
    index: 'reference',
    components: 'components',
    directives: 'directives',
    pipes: 'pipes',
    services: 'services',
    utils: 'utils',
    validators: 'validators',
    interfaces: 'interfaces',
  },
  tokens: {
    index: 'tokens',
    colors: 'colors',
    sizing: 'sizing',
    typography: 'typography',
    density: 'density',
    motion: 'motion',
    builder: 'builder',
  },
  components: {
    index: 'components',
    alert: 'alert',
    anchor: 'anchor',
    avatar: 'avatar',
    charts: 'charts',
    sparkline: 'sparkline',
    gauge: 'gauge',
    barChart: 'bar-chart',
    donutChart: 'donut-chart',
    lineChart: 'line-chart',
    calendarHeatmap: 'calendar-heatmap',
    backTop: 'back-top',
    badge: 'badge',
    breadcrumbs: 'breadcrumbs',
    burger: 'burger',
    button: 'button',
    buttonGroup: 'button-group',
    calendar: 'calendar',
    card: 'card',
    carousel: 'carousel',
    cascader: 'cascader',
    checkbox: 'checkbox',
    collapse: 'collapse',
    colorPicker: 'color-picker',
    commandPalette: 'command-palette',
    compare: 'compare',
    contextMenu: 'context-menu',
    counter: 'counter',
    datePicker: 'date-picker',
    dialog: 'dialog',
    divider: 'divider',
    drawer: 'drawer',
    editor: 'editor',
    empty: 'empty',
    form: 'form',
    formField: 'form-field',
    icon: 'icon',
    lightbox: 'lightbox',
    imageCropper: 'image-cropper',
    input: 'input',
    inputNumber: 'input-number',
    layout: 'layout',
    list: 'list',
    inputOtp: 'input-otp',
    keyboard: 'keyboard',
    knob: 'knob',
    markdown: 'markdown',
    mention: 'mention',
    meterGroup: 'meter-group',
    pageHeader: 'page-header',
    result: 'result',
    speedDial: 'speed-dial',
    splitter: 'splitter',
    statistic: 'statistic',
    timeline: 'timeline',
    toolbar: 'toolbar',
    descriptions: 'descriptions',
    popconfirm: 'popconfirm',
    popover: 'popover',
    progress: 'progress',
    qrCode: 'qrcode',
    radio: 'radio',
    rating: 'rating',
    schemaForm: 'schema-form',
    segmented: 'segmented',
    skeleton: 'skeleton',
    slider: 'slider',
    spinner: 'spinner',
    stepper: 'stepper',
    switch: 'switch',
    tabs: 'tabs',
    typography: 'typography',
    textarea: 'textarea',
    'event-calendar': 'event-calendar',
    transfer: 'transfer',
    toast: 'toast',
    tree: 'tree',
    graph: 'graph',
    select: 'select',
    sidebar: 'sidebar',
    dropdown: 'dropdown',
    fileUpload: 'file-upload',
    pagination: 'pagination',
    pullToRefresh: 'pull-to-refresh',
    table: 'table',
    virtualScroll: 'virtual-scroll',
    sortableList: 'sortable-list',
    window: 'window',
  },
  directives: {
    index: 'directives',
    affix: 'affix',
    autofocus: 'autofocus',
    autosize: 'autosize',
    clickOutside: 'click-outside',
    copyToClipboard: 'copy-to-clipboard',
    typography: 'typography',
  },
  // Visual effects + animations. Mixed bag of in-house components and
  // ports of reactbits.dev effects (attribution in each file).
  bits: {
    index: 'bits',
    borderGlow: 'border-glow',
    aurora: 'aurora',
    marquee: 'marquee',
    confetti: 'confetti',
    // Reactbits ports (built in follow-up commits)
    spotlightCard: 'spotlight-card',
    tiltCard: 'tilt-card',
    clickSpark: 'click-spark',
    waves: 'waves',
    starBorder: 'star-border',
    splashCursor: 'splash-cursor',
    splitText: 'split-text',
    blurText: 'blur-text',
    shinyText: 'shiny-text',
    gradientText: 'gradient-text',
    rotatingText: 'rotating-text',
    typewriter: 'typewriter',
    decryptText: 'decrypt-text',
    glitchText: 'glitch-text',
    fuzzyText: 'fuzzy-text',
    fallingText: 'falling-text',
    circularText: 'circular-text',
  },
  pipes: {
    index: 'pipes',
    wrNumber: 'wr-number',
    wrBytes: 'wr-bytes',
    wrDate: 'wr-date',
    wrTruncate: 'wr-truncate',
    wrMark: 'wr-mark',
    wrPlural: 'wr-plural',
    wrRange: 'wr-range',
  },
  services: {
    index: 'services',
    theme: 'theme',
    scroll: 'scroll',
    hotkey: 'hotkey',
    media: 'media',
    platform: 'platform',
    meta: 'meta',
    storage: 'storage',
    i18n: 'i18n',
    density: 'density',
    clipboard: 'clipboard',
    cookie: 'cookie',
    loadingBar: 'loading-bar',
    tour: 'tour',
  },
  utils: {
    index: 'utils',
    types: 'types',
    // Math
    clamp: 'clamp',
    round: 'round',
    numAttr: 'num-attr',
    // Css helpers
    toClassList: 'to-class-list',
    resolveCssSize: 'resolve-css-size',
    getRootFontSize: 'get-root-font-size',
    // Ids
    randomId: 'random-id',
    // Type guards
    isDefined: 'is-defined',
    isNonEmptyArray: 'is-non-empty-array',
    isObservable: 'is-observable',
    // Keyboard
    keys: 'keys',
    hasModifier: 'has-modifier',
    isComposing: 'is-composing',
    isPrintableKey: 'is-printable-key',
    // Functional primitives
    noop: 'noop',
    badgeLog: 'badge-log',
    debounce: 'debounce',
    throttle: 'throttle',
    // Focus
    getFocusableElements: 'get-focusable-elements',
    trapFocus: 'trap-focus',
  },
  typography: {
    index: 'typography',
    overview: 'overview',
    headings: 'headings',
    paragraphs: 'paragraphs',
    lists: 'lists',
    links: 'links',
    text: 'text',
    code: 'code',
    keyboard: 'keyboard',
  },
  translate: {
    index: 'translate',
    overview: 'overview',
    setup: 'setup',
    usage: 'usage',
    scopes: 'scopes',
    interpolation: 'interpolation',
    api: 'api',
  },
  interfaces: {
    index: 'interfaces',
    overview: 'overview',
    common: 'common',
    theme: 'theme',
    catalog: 'catalog',
  },
  validators: {
    index: 'validators',
    noWhitespace: 'no-whitespace',
    hexColor: 'hex-color',
    url: 'url',
    cardNumber: 'card-number',
    cvc: 'cvc',
    iban: 'iban',
    match: 'match',
    matchFields: 'match-fields',
    oneOf: 'one-of',
    minDate: 'min-date',
    maxDate: 'max-date',
  },
};
