/**
 * Every route the site has: the segment, the absolute URL, and the title it is
 * shown under.
 *
 * One tree instead of two sources. The slugs lived here and the titles lived
 * in the sidebar configs, which repeated the URL beside each one — 209 rows of
 * `{ title: 'Bar Chart', url: ['/charts', 'bar-chart'] }` that nothing held to
 * the route tree, so a renamed slug left a nav row pointing at a 404. A config
 * REFERENCES a node now and takes both from it.
 *
 * Plain values, written out. There was briefly a `defineRoutes()` that walked
 * this tree and computed each `url` from its parent — a recursive resolver and
 * two mapped types, to save typing a prefix into a file nobody edits by hand.
 *
 * Imported as `#routes`.
 */

/** One route: its own segment, the absolute path, and its title. */
export interface WrRoute {
  readonly path: string;
  readonly url: string;
  readonly title: string;
}

/** The site root. */
export const HOME: WrRoute = { path: '', url: '/', title: 'ngwr' };

export const ROUTES = {
  icons: {
    path: 'icons',
    url: '/icons',
    title: 'Icons',
    overview: { path: 'overview', url: '/icons/overview', title: 'Overview' },
    lucide: { path: 'lucide', url: '/icons/lucide', title: 'Lucide' },
    feather: { path: 'feather', url: '/icons/feather', title: 'Feather' },
    tabler: { path: 'tabler', url: '/icons/tabler', title: 'Tabler' },
    phosphor: { path: 'phosphor', url: '/icons/phosphor', title: 'Phosphor' },
    heroicons: { path: 'heroicons', url: '/icons/heroicons', title: 'Heroicons' },
    iconoir: { path: 'iconoir', url: '/icons/iconoir', title: 'Iconoir' },
    radix: { path: 'radix', url: '/icons/radix', title: 'Radix' },
    bootstrap: { path: 'bootstrap', url: '/icons/bootstrap', title: 'Bootstrap' },
  },
  docs: {
    path: 'docs',
    url: '/docs',
    title: 'Docs',
    introduction: { path: 'introduction', url: '/docs/introduction', title: 'Introduction' },
    installation: { path: 'installation', url: '/docs/installation', title: 'Installation' },
    configuration: { path: 'configuration', url: '/docs/configuration', title: 'Configuration' },
    migration: { path: 'migration', url: '/docs/migration', title: 'Migration' },
    skills: { path: 'skills', url: '/docs/skills', title: 'Skills' },
    mcp: { path: 'mcp-server', url: '/docs/mcp-server', title: 'MCP Server' },
  },
  charts: {
    path: 'charts',
    url: '/charts',
    title: 'Charts',
    barChart: { path: 'bar-chart', url: '/charts/bar-chart', title: 'Bar Chart' },
    calendarHeatmap: { path: 'calendar-heatmap', url: '/charts/calendar-heatmap', title: 'Calendar Heatmap' },
    donutChart: { path: 'donut-chart', url: '/charts/donut-chart', title: 'Donut Chart' },
    gauge: { path: 'gauge', url: '/charts/gauge', title: 'Gauge' },
    lineChart: { path: 'line-chart', url: '/charts/line-chart', title: 'Line Chart' },
    meterGroup: { path: 'meter-group', url: '/charts/meter-group', title: 'Meter Group' },
    sparkline: { path: 'sparkline', url: '/charts/sparkline', title: 'Sparkline' },
  },
  guides: {
    path: 'guides',
    url: '/guides',
    title: 'Guides',
    theming: { path: 'theming', url: '/guides/theming', title: 'Theming' },
    grid: { path: 'grid', url: '/guides/grid', title: 'Grid' },
    forms: { path: 'forms', url: '/guides/forms', title: 'Reactive forms' },
    overlay: { path: 'overlay', url: '/guides/overlay', title: 'Overlay' },
    mobile: { path: 'mobile', url: '/guides/mobile', title: 'Mobile & responsive' },
    keyboard: { path: 'keyboard', url: '/guides/keyboard', title: 'Keyboard' },
    ssr: { path: 'ssr', url: '/guides/ssr', title: 'Server-side rendering' },
    testing: { path: 'testing', url: '/guides/testing', title: 'Testing' },
    csp: { path: 'csp', url: '/guides/csp', title: 'Content Security Policy' },
    tokens: {
      path: 'tokens',
      url: '/guides/tokens',
      title: 'Design tokens',
      colors: { path: 'colors', url: '/guides/tokens/colors', title: 'Colors' },
      sizing: { path: 'sizing', url: '/guides/tokens/sizing', title: 'Sizing' },
      typography: { path: 'typography', url: '/guides/tokens/typography', title: 'Typography' },
      density: { path: 'density', url: '/guides/tokens/density', title: 'Density' },
      motion: { path: 'motion', url: '/guides/tokens/motion', title: 'Motion' },
      builder: { path: 'builder', url: '/guides/tokens/builder', title: 'Theme builder' },
    },
    color: { path: 'color', url: '/guides/color', title: 'Colour' },
    typography: {
      path: 'typography',
      url: '/guides/typography',
      title: 'Typography',
      overview: { path: 'overview', url: '/guides/typography/overview', title: 'Overview' },
      headings: { path: 'headings', url: '/guides/typography/headings', title: 'Headings' },
      paragraphs: { path: 'paragraphs', url: '/guides/typography/paragraphs', title: 'Paragraphs' },
      lists: { path: 'lists', url: '/guides/typography/lists', title: 'Lists' },
      links: { path: 'links', url: '/guides/typography/links', title: 'Links' },
      text: { path: 'text', url: '/guides/typography/text', title: 'Text' },
      code: { path: 'code', url: '/guides/typography/code', title: 'Code' },
      keyboard: { path: 'keyboard', url: '/guides/typography/keyboard', title: 'Keyboard' },
    },
    translations: {
      path: 'translations',
      url: '/guides/translations',
      title: 'Translations',
      overview: { path: 'overview', url: '/guides/translations/overview', title: 'Overview' },
      setup: { path: 'setup', url: '/guides/translations/setup', title: 'Setup & loaders' },
      usage: { path: 'usage', url: '/guides/translations/usage', title: 'Usage in templates' },
      scopes: { path: 'scopes', url: '/guides/translations/scopes', title: 'Scopes' },
      interpolation: { path: 'interpolation', url: '/guides/translations/interpolation', title: 'Interpolation' },
      api: { path: 'api', url: '/guides/translations/api', title: 'API' },
    },
  },
  reference: {
    path: 'reference',
    url: '/reference',
    title: 'Reference',
    components: {
      path: 'components',
      url: '/reference/components',
      title: 'Components',
      alert: { path: 'alert', url: '/reference/components/alert', title: 'Alert' },
      anchor: { path: 'anchor', url: '/reference/components/anchor', title: 'Anchor' },
      avatar: { path: 'avatar', url: '/reference/components/avatar', title: 'Avatar' },
      backTop: { path: 'back-top', url: '/reference/components/back-top', title: 'Back to Top' },
      badge: { path: 'badge', url: '/reference/components/badge', title: 'Badge' },
      breadcrumbs: { path: 'breadcrumbs', url: '/reference/components/breadcrumbs', title: 'Breadcrumbs' },
      burger: { path: 'burger', url: '/reference/components/burger', title: 'Burger' },
      button: { path: 'button', url: '/reference/components/button', title: 'Button' },
      buttonGroup: { path: 'button-group', url: '/reference/components/button-group', title: 'Button Group' },
      calendar: { path: 'calendar', url: '/reference/components/calendar', title: 'Calendar' },
      card: { path: 'card', url: '/reference/components/card', title: 'Card' },
      carousel: { path: 'carousel', url: '/reference/components/carousel', title: 'Carousel' },
      cascader: { path: 'cascader', url: '/reference/components/cascader', title: 'Cascader' },
      checkbox: { path: 'checkbox', url: '/reference/components/checkbox', title: 'Checkbox' },
      collapse: { path: 'collapse', url: '/reference/components/collapse', title: 'Collapse' },
      colorPicker: { path: 'color-picker', url: '/reference/components/color-picker', title: 'Color Picker' },
      commandPalette: {
        path: 'command-palette',
        url: '/reference/components/command-palette',
        title: 'Command Palette',
      },
      compare: { path: 'compare', url: '/reference/components/compare', title: 'Compare' },
      contextMenu: { path: 'context-menu', url: '/reference/components/context-menu', title: 'Context Menu' },
      counter: { path: 'counter', url: '/reference/components/counter', title: 'Counter' },
      datePicker: { path: 'date-picker', url: '/reference/components/date-picker', title: 'Date Picker' },
      dialog: { path: 'dialog', url: '/reference/components/dialog', title: 'Dialog' },
      divider: { path: 'divider', url: '/reference/components/divider', title: 'Divider' },
      drawer: { path: 'drawer', url: '/reference/components/drawer', title: 'Drawer' },
      editor: { path: 'editor', url: '/reference/components/editor', title: 'Editor' },
      eventCalendar: { path: 'event-calendar', url: '/reference/components/event-calendar', title: 'Event Calendar' },
      empty: { path: 'empty', url: '/reference/components/empty', title: 'Empty' },
      form: { path: 'form', url: '/reference/components/form', title: 'Form' },
      formField: { path: 'form-field', url: '/reference/components/form-field', title: 'Form Field' },
      icon: { path: 'icon', url: '/reference/components/icon', title: 'Icon' },
      lightbox: { path: 'lightbox', url: '/reference/components/lightbox', title: 'Lightbox' },
      imageCropper: { path: 'image-cropper', url: '/reference/components/image-cropper', title: 'Image Cropper' },
      input: { path: 'input', url: '/reference/components/input', title: 'Input' },
      inputNumber: { path: 'input-number', url: '/reference/components/input-number', title: 'Input Number' },
      layout: { path: 'layout', url: '/reference/components/layout', title: 'Layout' },
      list: { path: 'list', url: '/reference/components/list', title: 'List' },
      inputOtp: { path: 'input-otp', url: '/reference/components/input-otp', title: 'Input OTP' },
      keyboard: { path: 'keyboard', url: '/reference/components/keyboard', title: 'Keyboard' },
      knob: { path: 'knob', url: '/reference/components/knob', title: 'Knob' },
      markdown: { path: 'markdown', url: '/reference/components/markdown', title: 'Markdown' },
      mention: { path: 'mention', url: '/reference/components/mention', title: 'Mention' },
      pageHeader: { path: 'page-header', url: '/reference/components/page-header', title: 'Page Header' },
      result: { path: 'result', url: '/reference/components/result', title: 'Result' },
      speedDial: { path: 'speed-dial', url: '/reference/components/speed-dial', title: 'Speed Dial' },
      splitter: { path: 'splitter', url: '/reference/components/splitter', title: 'Splitter' },
      statistic: { path: 'statistic', url: '/reference/components/statistic', title: 'Statistic' },
      timeline: { path: 'timeline', url: '/reference/components/timeline', title: 'Timeline' },
      toolbar: { path: 'toolbar', url: '/reference/components/toolbar', title: 'Toolbar' },
      descriptions: { path: 'descriptions', url: '/reference/components/descriptions', title: 'Descriptions' },
      popconfirm: { path: 'popconfirm', url: '/reference/components/popconfirm', title: 'Popconfirm' },
      popover: { path: 'popover', url: '/reference/components/popover', title: 'Popover' },
      progress: { path: 'progress', url: '/reference/components/progress', title: 'Progress' },
      qrCode: { path: 'qrcode', url: '/reference/components/qrcode', title: 'QR' },
      radio: { path: 'radio', url: '/reference/components/radio', title: 'Radio' },
      rating: { path: 'rating', url: '/reference/components/rating', title: 'Rating' },
      schemaForm: { path: 'schema-form', url: '/reference/components/schema-form', title: 'Schema Form' },
      segmented: { path: 'segmented', url: '/reference/components/segmented', title: 'Segmented' },
      skeleton: { path: 'skeleton', url: '/reference/components/skeleton', title: 'Skeleton' },
      slider: { path: 'slider', url: '/reference/components/slider', title: 'Slider' },
      spinner: { path: 'spinner', url: '/reference/components/spinner', title: 'Spinner' },
      stepper: { path: 'stepper', url: '/reference/components/stepper', title: 'Stepper' },
      switch: { path: 'switch', url: '/reference/components/switch', title: 'Switch' },
      tabs: { path: 'tabs', url: '/reference/components/tabs', title: 'Tabs' },
      typography: { path: 'typography', url: '/reference/components/typography', title: 'Typography' },
      textarea: { path: 'textarea', url: '/reference/components/textarea', title: 'Textarea' },
      transfer: { path: 'transfer', url: '/reference/components/transfer', title: 'Transfer' },
      toast: { path: 'toast', url: '/reference/components/toast', title: 'Toast' },
      tree: { path: 'tree', url: '/reference/components/tree', title: 'Tree' },
      graph: { path: 'graph', url: '/reference/components/graph', title: 'Graph' },
      select: { path: 'select', url: '/reference/components/select', title: 'Select' },
      sidebar: { path: 'sidebar', url: '/reference/components/sidebar', title: 'Sidebar' },
      dropdown: { path: 'dropdown', url: '/reference/components/dropdown', title: 'Dropdown' },
      fileUpload: { path: 'file-upload', url: '/reference/components/file-upload', title: 'File Upload' },
      pagination: { path: 'pagination', url: '/reference/components/pagination', title: 'Pagination' },
      pullToRefresh: {
        path: 'pull-to-refresh',
        url: '/reference/components/pull-to-refresh',
        title: 'Pull to Refresh',
      },
      table: { path: 'table', url: '/reference/components/table', title: 'Table' },
      virtualScroll: { path: 'virtual-scroll', url: '/reference/components/virtual-scroll', title: 'Virtual Scroll' },
      sortableList: { path: 'sortable-list', url: '/reference/components/sortable-list', title: 'Sortable List' },
      window: { path: 'window', url: '/reference/components/window', title: 'Window' },
    },
    directives: {
      path: 'directives',
      url: '/reference/directives',
      title: 'Directives',
      affix: { path: 'affix', url: '/reference/directives/affix', title: 'wrAffix' },
      autofocus: { path: 'autofocus', url: '/reference/directives/autofocus', title: 'wrAutofocus' },
      autosize: { path: 'autosize', url: '/reference/directives/autosize', title: 'wrAutosize' },
      clickOutside: { path: 'click-outside', url: '/reference/directives/click-outside', title: 'wrClickOutside' },
      copyToClipboard: {
        path: 'copy-to-clipboard',
        url: '/reference/directives/copy-to-clipboard',
        title: 'wrCopyToClipboard',
      },
      typography: { path: 'typography', url: '/reference/directives/typography', title: 'wrTypography API' },
    },
    pipes: {
      path: 'pipes',
      url: '/reference/pipes',
      title: 'Pipes',
      wrNumber: { path: 'wr-number', url: '/reference/pipes/wr-number', title: 'wrNumber' },
      wrBytes: { path: 'wr-bytes', url: '/reference/pipes/wr-bytes', title: 'wrBytes' },
      wrDate: { path: 'wr-date', url: '/reference/pipes/wr-date', title: 'wrDate' },
      wrTruncate: { path: 'wr-truncate', url: '/reference/pipes/wr-truncate', title: 'wrTruncate' },
      wrMark: { path: 'wr-mark', url: '/reference/pipes/wr-mark', title: 'wrMark' },
      wrPlural: { path: 'wr-plural', url: '/reference/pipes/wr-plural', title: 'wrPlural' },
      wrRange: { path: 'wr-range', url: '/reference/pipes/wr-range', title: 'wrRange' },
    },
    services: {
      path: 'services',
      url: '/reference/services',
      title: 'Services',
      theme: { path: 'theme', url: '/reference/services/theme', title: 'WrTheme' },
      scroll: { path: 'scroll', url: '/reference/services/scroll', title: 'WrScroll' },
      hotkey: { path: 'hotkey', url: '/reference/services/hotkey', title: 'WrHotkey' },
      media: { path: 'media', url: '/reference/services/media', title: 'WrMedia' },
      platform: { path: 'platform', url: '/reference/services/platform', title: 'WrPlatform' },
      meta: { path: 'meta', url: '/reference/services/meta', title: 'WrMeta' },
      storage: { path: 'storage', url: '/reference/services/storage', title: 'WrStorage' },
      i18n: { path: 'i18n', url: '/reference/services/i18n', title: 'WrI18n' },
      density: { path: 'density', url: '/reference/services/density', title: 'WrDensity' },
      clipboard: { path: 'clipboard', url: '/reference/services/clipboard', title: 'WrClipboard' },
      cookie: { path: 'cookie', url: '/reference/services/cookie', title: 'WrCookie' },
      loadingBar: { path: 'loading-bar', url: '/reference/services/loading-bar', title: 'WrLoadingBar' },
      tour: { path: 'tour', url: '/reference/services/tour', title: 'WrTour' },
    },
    utils: {
      path: 'utils',
      url: '/reference/utils',
      title: 'Utils',
      types: { path: 'types', url: '/reference/utils/types', title: 'Types' },
      clamp: { path: 'clamp', url: '/reference/utils/clamp', title: 'clamp' },
      round: { path: 'round', url: '/reference/utils/round', title: 'round' },
      numAttr: { path: 'num-attr', url: '/reference/utils/num-attr', title: 'numAttr' },
      toClassList: { path: 'to-class-list', url: '/reference/utils/to-class-list', title: 'toClassList' },
      resolveCssSize: { path: 'resolve-css-size', url: '/reference/utils/resolve-css-size', title: 'resolveCssSize' },
      getRootFontSize: {
        path: 'get-root-font-size',
        url: '/reference/utils/get-root-font-size',
        title: 'getRootFontSize',
      },
      randomId: { path: 'random-id', url: '/reference/utils/random-id', title: 'randomId' },
      isDefined: { path: 'is-defined', url: '/reference/utils/is-defined', title: 'isDefined' },
      isNonEmptyArray: {
        path: 'is-non-empty-array',
        url: '/reference/utils/is-non-empty-array',
        title: 'isNonEmptyArray',
      },
      isObservable: { path: 'is-observable', url: '/reference/utils/is-observable', title: 'isObservable' },
      keys: { path: 'keys', url: '/reference/utils/keys', title: 'KEYS' },
      hasModifier: { path: 'has-modifier', url: '/reference/utils/has-modifier', title: 'hasModifier' },
      isComposing: { path: 'is-composing', url: '/reference/utils/is-composing', title: 'isComposing' },
      isPrintableKey: { path: 'is-printable-key', url: '/reference/utils/is-printable-key', title: 'isPrintableKey' },
      noop: { path: 'noop', url: '/reference/utils/noop', title: 'noop' },
      badgeLog: { path: 'badge-log', url: '/reference/utils/badge-log', title: 'badgeLog' },
      debounce: { path: 'debounce', url: '/reference/utils/debounce', title: 'debounce' },
      throttle: { path: 'throttle', url: '/reference/utils/throttle', title: 'throttle' },
      getFocusableElements: {
        path: 'get-focusable-elements',
        url: '/reference/utils/get-focusable-elements',
        title: 'getFocusableElements',
      },
      trapFocus: { path: 'trap-focus', url: '/reference/utils/trap-focus', title: 'trapFocus' },
    },
    validators: {
      path: 'validators',
      url: '/reference/validators',
      title: 'Validators',
      // `urlValidator`, not `url`: a child key named `url` shadows the node's
      // own field, and the three field names are reserved for that reason.
      urlValidator: { path: 'url', url: '/reference/validators/url', title: 'url' },
      noWhitespace: { path: 'no-whitespace', url: '/reference/validators/no-whitespace', title: 'noWhitespace' },
      hexColor: { path: 'hex-color', url: '/reference/validators/hex-color', title: 'hexColor' },
      cardNumber: { path: 'card-number', url: '/reference/validators/card-number', title: 'cardNumber' },
      cvc: { path: 'cvc', url: '/reference/validators/cvc', title: 'cvc' },
      iban: { path: 'iban', url: '/reference/validators/iban', title: 'iban' },
      match: { path: 'match', url: '/reference/validators/match', title: 'match' },
      matchFields: { path: 'match-fields', url: '/reference/validators/match-fields', title: 'matchFields' },
      oneOf: { path: 'one-of', url: '/reference/validators/one-of', title: 'oneOf' },
      minDate: { path: 'min-date', url: '/reference/validators/min-date', title: 'minDate' },
      maxDate: { path: 'max-date', url: '/reference/validators/max-date', title: 'maxDate' },
    },
    interfaces: {
      path: 'interfaces',
      url: '/reference/interfaces',
      title: 'Interfaces',
      overview: { path: 'overview', url: '/reference/interfaces/overview', title: 'Overview' },
      common: { path: 'common', url: '/reference/interfaces/common', title: 'Common' },
      theme: { path: 'theme', url: '/reference/interfaces/theme', title: 'Theme' },
      catalog: { path: 'catalog', url: '/reference/interfaces/catalog', title: 'Catalog' },
    },
  },
  bits: {
    path: 'bits',
    url: '/bits',
    title: 'Bits',
    borderGlow: { path: 'border-glow', url: '/bits/border-glow', title: 'Border Glow' },
    aurora: { path: 'aurora', url: '/bits/aurora', title: 'Aurora' },
    marquee: { path: 'marquee', url: '/bits/marquee', title: 'Marquee' },
    confetti: { path: 'confetti', url: '/bits/confetti', title: 'Confetti' },
    spotlightCard: { path: 'spotlight-card', url: '/bits/spotlight-card', title: 'Spotlight Card' },
    tiltCard: { path: 'tilt-card', url: '/bits/tilt-card', title: 'Tilt Card' },
    clickSpark: { path: 'click-spark', url: '/bits/click-spark', title: 'Click Spark' },
    waves: { path: 'waves', url: '/bits/waves', title: 'Waves' },
    starBorder: { path: 'star-border', url: '/bits/star-border', title: 'Star Border' },
    splashCursor: { path: 'splash-cursor', url: '/bits/splash-cursor', title: 'Splash Cursor' },
    splitText: { path: 'split-text', url: '/bits/split-text', title: 'Split Text' },
    blurText: { path: 'blur-text', url: '/bits/blur-text', title: 'Blur Text' },
    shinyText: { path: 'shiny-text', url: '/bits/shiny-text', title: 'Shiny Text' },
    gradientText: { path: 'gradient-text', url: '/bits/gradient-text', title: 'Gradient Text' },
    rotatingText: { path: 'rotating-text', url: '/bits/rotating-text', title: 'Rotating Text' },
    typewriter: { path: 'typewriter', url: '/bits/typewriter', title: 'Typewriter' },
    decryptText: { path: 'decrypt-text', url: '/bits/decrypt-text', title: 'Decrypt Text' },
    glitchText: { path: 'glitch-text', url: '/bits/glitch-text', title: 'Glitch Text' },
    fuzzyText: { path: 'fuzzy-text', url: '/bits/fuzzy-text', title: 'Fuzzy Text' },
    fallingText: { path: 'falling-text', url: '/bits/falling-text', title: 'Falling Text' },
    circularText: { path: 'circular-text', url: '/bits/circular-text', title: 'Circular Text' },
  },
} as const;
