/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/**
 * Generates per-icon barrels for every `ngwr/icon/adapters/<set>` adapter
 * by walking the upstream packages at build time. The generator runs
 * once on demand (`pnpm icons:build`) — the result is committed so
 * ng-packagr can build each adapter without re-running the generator
 * every time.
 *
 * Output: `projects/lib/icon/adapters/<set>/public-api.ts` (overwritten).
 *
 * Add a new adapter by writing a small entry below: peerDep package
 * name, the set's `<adapter>` function from `adapter.ts`, and any
 * filter / transform tweaks.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { info } from './lib/log/info';
import { ROOT_PATH } from './lib/paths/root';

interface Generator {
  /** Display name used in log lines. */
  readonly name: string;
  /** Lib subdir under `projects/lib/icon/adapters/`. */
  readonly dir: string;
  /** Upstream package — dynamically imported at build time. */
  readonly pkg: string;
  /** Filter symbols that aren't icons (helpers, types, etc.). */
  readonly accept?: (key: string, value: unknown) => boolean;
  /** Convert an upstream PascalCase identifier to a wr-icon kebab name. */
  readonly toKebab?: (key: string) => string;
  /** Adapter function name (imported from `./adapter`). */
  readonly adapter: string;
}

const GENERATORS: readonly Generator[] = [
  {
    name: 'Lucide',
    dir: 'lucide',
    pkg: 'lucide',
    // Lucide exports a few helpers (`createIcons`, `createElement`,
    // `icons`) that aren't IconNode arrays. Filter them out.
    accept: (_key, value) => Array.isArray(value),
    adapter: 'lucide',
  },
];

async function run(): Promise<void> {
  for (const gen of GENERATORS) {
    const result = await build(gen);
    info(`✓ ${gen.name}: generated ${result.count} icons → projects/lib/icon/adapters/${gen.dir}/public-api.ts`);
  }
}

async function build(gen: Generator): Promise<{ count: number }> {
  const mod = (await import(gen.pkg)) as Record<string, unknown>;
  const entries: { camel: string; pascal: string; kebab: string }[] = [];
  const seen = new Set<string>();

  for (const key of Object.keys(mod).sort()) {
    if (!isPascal(key)) continue;
    const value = mod[key];
    if (gen.accept && !gen.accept(key, value)) continue;

    const kebab = (gen.toKebab ?? pascalToKebab)(key);
    const camel = pascalToCamel(key);

    // Lucide exposes both canonical names AND legacy aliases (e.g.
    // `ArrowDownAZ` and `ArrowDownAz`). Both point at the same icon node
    // array; we emit just one export to keep the barrel lean.
    if (seen.has(camel)) continue;
    seen.add(camel);

    entries.push({ camel, pascal: key, kebab });
  }

  const importNames = entries.map(e => e.pascal).join(', ');
  const exportLines = entries.map(e => `export const ${e.camel} = ${gen.adapter}('${e.kebab}', ${e.pascal});`).join('\n');

  const content = `${HEADER(gen)}import { ${importNames} } from '${packageOf(gen.dir)}';

import { ${gen.adapter} } from './adapter';

${exportLines}
`;

  const outPath = resolve(ROOT_PATH, `projects/lib/icon/adapters/${gen.dir}/public-api.ts`);
  writeFileSync(outPath, content);
  return { count: entries.length };
}

function HEADER(gen: Generator): string {
  return `/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

// AUTO-GENERATED by scripts/build-icon-adapters.ts ($${gen.name}). Do not
// edit by hand — re-run \`pnpm icons:build\` after updating the upstream
// package.

/* eslint-disable */

`;
}

function packageOf(dir: string): string {
  // Adapter dir name matches the upstream package name for the first 4
  // sets. Override here once an adapter diverges (e.g. phosphor/regular
  // → @phosphor-icons/core).
  return dir;
}

function isPascal(key: string): boolean {
  return /^[A-Z]/.test(key);
}

/**
 * JS / TS reserved words that can't be used as `export const <name>`.
 * Lucide ships icons named `Import`, `Type`, `Function` etc. We append
 * `Icon` to keep them valid identifiers.
 */
const RESERVED = new Set([
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'implements',
  'import',
  'in',
  'instanceof',
  'interface',
  'let',
  'new',
  'null',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'static',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
]);

function pascalToCamel(key: string): string {
  const camel = key.charAt(0).toLowerCase() + key.slice(1);
  return RESERVED.has(camel) ? `${camel}Icon` : camel;
}

function pascalToKebab(key: string): string {
  return key.replace(/([a-z\d])([A-Z])/g, '$1-$2').toLowerCase();
}

await run();
