/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/**
 * Fails the build when a state or intent is told apart by COLOUR and nothing
 * else, without saying why that is acceptable.
 *
 * Why this exists, and why it is a source check rather than a browser one. The
 * nine intents cannot be told apart by lightness: v11 deepened five of them so
 * `_contrast()` would pick a WHITE label, and tuning nine colours to one ratio
 * against the same two candidates IS tuning them to one luminance. Measured off
 * `$base-colors`, six of the nine sit inside a 1.06:1 band and `success`
 * against `danger` is 1.004:1 — the same grey. So for a reader with red-green
 * colour blindness, roughly one man in twelve, a `--success` modifier and a
 * `--danger` modifier that differ only in colour are the same element.
 *
 * No runtime gate can report this. axe ships no rule for WCAG 1.4.1, which is
 * why `check:a11y`, `check:contrast` and `check:state-a11y` are all green over
 * a catalog where a sweep upheld thirty-two findings. And no assertion about
 * the COLOURS is satisfiable — the intents have to share a luminance to keep
 * their labels legible, so "make them differ" is a contradiction, not a target.
 * What is checkable is a source fact: does a non-colour declaration exist.
 *
 * What it does NOT do is ban colour-only state. Plenty is correct — a
 * `--wr-color-danger` border against the default `--wr-color-outline` differs
 * in LIGHTNESS, not only in hue; a sequential heat scale that ramps opacity
 * over one hue survives greyscale intact; and a modifier whose channel lives in
 * a SIBLING rule (a `::before` tick, a moving thumb, a different glyph in the
 * template) is fine and simply not visible from the block itself. The rule is
 * that such a block carries a marker naming the channel:
 *
 *     // color-ok: the base border is transparent, so this paints an underline
 *     &--active {
 *       border-bottom-color: var(--wr-color-primary);
 *     }
 *
 * So this is a "say why" gate rather than a "don't" gate — the same shape as
 * `check:rtl` and `check:tokens`, and for the same reason: the exceptions are
 * real, so the only thing worth enforcing is that each one was a decision.
 *
 * Two models already in the tree, worth copying instead of writing a marker:
 * `wr-statistic` draws two genuinely different triangles for up and down, and
 * `wr-calendar-heatmap` ramps opacity over a single hue.
 *
 * THREE THINGS IT CANNOT SEE, and they are worth knowing before trusting a
 * green run. It reads one concrete selector at a time, so a per-intent rule
 * GENERATED by an `@each` over `$base-colors` is invisible — which is how most
 * of the catalog paints its nine intents, and it is why a green run here is not
 * a claim that two intents can be told apart, only that no hand-written block
 * relies on hue alone. It judges a block's OWN declarations, so a channel in a
 * sibling rule needs the marker to point at it. And a few real silhouettes are
 * spelled with colour-valued properties — a hollow dot is `background:
 * transparent` plus an inset ring — which read here as colour and need the
 * marker too.
 *
 * Wired into `lint`, like `check:rtl` and `check:tokens`: `ci.yml`,
 * `deploy.yml` and `publish.yml` all run `pnpm lint` already.
 */

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const LIB = join(ROOT, 'projects/lib');

/**
 * The marker is looked for in the CONTIGUOUS comment block directly above the
 * selector, however many lines that runs to.
 *
 * `check:rtl` counts a fixed three lines instead, and the difference is the
 * kind of thing being excused. A physical property needs a clause; "what tells
 * these two states apart other than hue" needs a sentence or three, and a
 * fixed reach silently stopped seeing markers whose explanation was honest
 * enough to need a fourth line. A blank line ends the run, so a marker still
 * cannot reach past the rule it sits above.
 */
const MARKER = 'color-ok:';

/**
 * Modifier names that carry MEANING rather than geometry.
 *
 * Curated rather than "anything after `--`", and the distinction is the whole
 * accuracy of the check: `--sm`, `--outlined`, `--pill` and `--vertical` are
 * shape and size, where a colour-only rule says nothing at all about state, and
 * treating them as findings would bury the real ones. What is listed here is
 * the set a reader has to TELL APART to use the component — a status, a
 * selection, a validity, or one of the nine intents.
 */
const STATEFUL = new RegExp(
  [
    // Selection and navigation.
    String.raw`selected|active|current|checked|indeterminate|open|expanded|collapsed`,
    // Validity and progress.
    String.raw`invalid|error|valid|complete|completed|pending|reachable|loading`,
    // The nine intents, plus the names components give them.
    String.raw`primary|secondary|success|warning|danger|info|neutral|offline|medium|light|dark`,
    // Direction of change — a statistic, a trend, a diff.
    String.raw`up|down|added|removed`,
  ].join('|')
);

/**
 * Declarations that paint and do nothing else.
 *
 * `box-shadow` is here deliberately even though it can carry a shape: under
 * `forced-colors` every shadow is dropped outright, so a shadow is never the
 * channel a reader who needs one can rely on. Custom properties are included by
 * NAME pattern below rather than listed, since a component's own
 * `--wr-<name>-{bg,border,accent,ink,color}` is the usual way an intent reaches
 * a stylesheet here.
 */
const COLOUR_PROPERTIES = new Set([
  'color',
  'background',
  'background-color',
  'background-image',
  'border-color',
  'border-top-color',
  'border-right-color',
  'border-bottom-color',
  'border-left-color',
  'border-inline-color',
  'border-inline-start-color',
  'border-inline-end-color',
  'border-block-color',
  'border-block-start-color',
  'border-block-end-color',
  'outline-color',
  'fill',
  'stroke',
  'box-shadow',
  'accent-color',
  'caret-color',
  'text-decoration-color',
  'column-rule-color',
]);

/** A component hook whose name says it carries a colour. */
const COLOUR_CUSTOM_PROPERTY = /^--wr-[\w-]*(?:color|bg|background|border|accent|ink|fill|stroke|shadow)\b/;

interface Finding {
  readonly file: string;
  readonly line: number;
  readonly selector: string;
  readonly properties: readonly string[];
}

function scssFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      // The theme layer declares the tokens rather than painting a state with
      // them; `check:tokens` is what answers for that file set.
      if (entry === 'theme') continue;
      out.push(...scssFiles(path));
    } else if (entry.endsWith('.scss')) out.push(path);
  }
  return out;
}

/** Strip comments so a `//` mention of a property is not read as a declaration. */
function withoutComments(source: string): string {
  return source.replace(/\/\*[\s\S]*?\*\//g, match => match.replace(/[^\n]/g, ' ')).replace(/\/\/[^\n]*/g, '');
}

function isColourProperty(name: string): boolean {
  return COLOUR_PROPERTIES.has(name) || COLOUR_CUSTOM_PROPERTY.test(name);
}

/**
 * The declarations a block writes ITSELF, at its own nesting level.
 *
 * Walked by brace depth rather than sliced up to the first `{`, because a
 * nested rule may come BEFORE a declaration — and the sliced version then read
 * an empty body, found no properties, and let the block through. It is a
 * false NEGATIVE, which is the worse direction for a gate: nothing is printed,
 * so nothing looks wrong. Found by a self-test rather than by review.
 */
function ownDeclarations(source: string, from: number): string[] {
  const own: string[] = [];
  let depth = 0;
  let segment = '';

  for (let i = from; i < source.length; i++) {
    const ch = source[i];
    if (ch === '{') {
      depth++;
      // Whatever preceded this brace was a selector, never a declaration.
      segment = '';
      continue;
    }
    if (ch === '}') {
      if (depth === 0) break;
      depth--;
      segment = '';
      continue;
    }
    if (depth > 0) continue;
    if (ch === ';') {
      const match = /^\s*([\w-]+)\s*:/.exec(segment);
      if (match) own.push(match[1]);
      segment = '';
      continue;
    }
    segment += ch;
  }

  return own;
}

/**
 * Does this block create a pseudo-element — `&::before` or `&::after` carrying
 * a `content` declaration — anywhere inside it?
 *
 * Scoped to the block by brace depth, so a sibling rule further down the file
 * cannot vouch for it.
 */
function createsPseudoElement(source: string, from: number): boolean {
  let depth = 0;
  let end = source.length;
  for (let i = from; i < source.length; i++) {
    if (source[i] === '{') depth++;
    else if (source[i] === '}') {
      if (depth === 0) {
        end = i;
        break;
      }
      depth--;
    }
  }

  const body = source.slice(from, end);
  for (const nested of body.matchAll(/([^{}();]*::(?:before|after)[^{}();]*)\{([^{}]*)\}/g)) {
    if (/(^|;)\s*content\s*:/.test(nested[2])) return true;
  }
  return false;
}

/**
 * Is there a `color-ok:` in the comment block immediately above this selector?
 *
 * Walks upward over `//` lines and stops at the first line that is not one — a
 * declaration, a brace, or a blank line. That last stop is what keeps a marker
 * from vouching for a rule it does not sit against.
 */
function markedAbove(lines: readonly string[], selectorLine: number): boolean {
  for (let i = selectorLine - 2; i >= 0; i--) {
    const text = lines[i].trim();
    if (!text.startsWith('//')) return false;
    if (text.includes(MARKER)) return true;
  }
  return false;
}

/**
 * Walk a stylesheet brace by brace, and judge each block on its OWN
 * declarations.
 *
 * Judging the whole subtree would excuse a colour-only modifier because some
 * descendant of it happens to set a width; judging only the own declarations is
 * the question actually being asked, which is "does this modifier, by itself,
 * change anything a reader without hue can see".
 */
function findings(): Finding[] {
  const found: Finding[] = [];

  for (const file of scssFiles(LIB)) {
    const raw = readFileSync(file, 'utf8');
    const source = withoutComments(raw);
    const rawLines = raw.split('\n');

    // Every `{` with the text that precedes it is a candidate selector.
    const openers = [...source.matchAll(/([^{}();]*)\{/g)];

    for (const opener of openers) {
      const selector = opener[1].trim().replace(/\s+/g, ' ');
      if (!selector || selector.startsWith('@')) continue;
      // A modifier, `&--x` or a literal `.wr-block--x`, naming a state.
      if (!new RegExp(String.raw`--(?:${STATEFUL.source})\b`).test(selector)) continue;

      const bodyStart = (opener.index ?? 0) + opener[0].length;
      const properties = ownDeclarations(source, bodyStart);
      // A nested `&::before` / `&::after` that declares `content` is a box this
      // modifier BRINGS INTO BEING — a bar, a tick, a dot that is not on the
      // element otherwise. That is the modifier's own channel and not something
      // "elsewhere", so it clears the block rather than needing a marker to
      // point at it. A nested DESCENDANT rule is the opposite case and still
      // does not count: `&--active &__icon` restyles something that is there
      // either way.
      if (createsPseudoElement(source, bodyStart)) continue;
      if (properties.length === 0) continue;
      if (properties.some(name => !isColourProperty(name))) continue;

      // Two positions matter and they are not the same line. The selector
      // pattern is `[^{}();]*`, which crosses newlines, so the match begins
      // right after the previous block closed — anchoring anything on it reads
      // several lines too high. So: report the BRACE's line, and look for the
      // marker above the selector's FIRST line, which for a multi-line selector
      // list is not the brace's. Getting that second part wrong put a marker
      // written directly above a two-line selector list out of reach.
      const line = source.slice(0, bodyStart - 1).split('\n').length;
      const matchStart = bodyStart - 1 - opener[1].length;
      const leading = opener[1].length - opener[1].trimStart().length;
      const selectorLine = source.slice(0, matchStart + leading).split('\n').length;
      if (markedAbove(rawLines, selectorLine)) continue;

      found.push({ file: relative(ROOT, file), line, selector, properties: [...new Set(properties)] });
    }
  }

  return found;
}

const found = findings();

if (found.length > 0) {
  console.error(`\n✖ ${found.length} state${found.length === 1 ? '' : 's'} told apart by colour alone:\n`);
  for (const { file, line, selector, properties } of found) {
    console.error(`  ${file}:${line}`);
    console.error(`    ${selector} → ${properties.join(', ')}`);
  }
  console.error(`
  Six of the nine intents sit inside a 1.06:1 band of relative luminance, and
  \`success\` against \`danger\` is 1.004:1 — the same grey. A modifier whose only
  declarations are colour is invisible to a reader with red-green colour
  blindness, and no gate but this one can see it: axe ships no WCAG 1.4.1 rule.

  Give the state a channel that is not hue — a glyph, a label, a weight, a
  border STYLE, an opacity ramp, a position. \`wr-statistic\` draws two different
  triangles; \`wr-calendar-heatmap\` ramps opacity over one hue.

  Or, if colour alone is right here — the cue separates in LIGHTNESS as well as
  hue, the scale is sequential, or the real channel lives in a sibling rule or
  in the template — say so above the selector:

    // color-ok: <what tells these apart besides hue>
`);
  process.exit(1);
}

console.log('✓ Colour — every state has a channel besides hue, or says why it needs none.');
