/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/**
 * Projects the library's signal API into the showcase as generated data, and
 * reports where a hand-written docs table still disagrees with the source.
 *
 * Two modes:
 *
 *   pnpm gen:api-docs          write projects/showcase/app/_core/generated/api.ts
 *   pnpm check:api-docs        compare hand-written tables against the source
 *
 * The check is the half that pays immediately: it turns "the docs drifted" from
 * something a human notices months later into a failing build. The 2026-08-07
 * audit found `skeleton` and `fuzzy-text` documenting defaults the code did not
 * have, `switch` missing its primary two-way model, `select` still listing an
 * input removed a major earlier, and four pages with no input table at all — all
 * of it invisible to every existing gate.
 *
 * Pages opt in to the generated data by replacing their hand-written array with
 * `API['WrFoo']`. Until a page does, the check keeps it honest.
 */

import { readFileSync, readdirSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

import { type ApiEntry, extractApi } from './lib/extract-api';
import { ROOT_PATH } from './lib/paths/root';

const OUT_DIR = resolve(ROOT_PATH, 'projects/showcase/app/_core/generated');
const OUT_FILE = join(OUT_DIR, 'api.ts');
const PAGES_ROOT = resolve(ROOT_PATH, 'projects/showcase/app');

function serialize(api: Map<string, ApiEntry>): string {
  const entries = [...api.entries()].sort(([a], [b]) => a.localeCompare(b));

  const body = entries
    .map(([klass, e]) => {
      const rows = e.rows
        .map(r => {
          const parts = [
            `name: ${JSON.stringify(r.name)}`,
            `description: ${JSON.stringify(r.description)}`,
            `type: ${JSON.stringify(r.type)}`,
            ...(r.required ? ['required: true'] : []),
            ...(r.default !== undefined ? [`default: ${JSON.stringify(r.default)}`] : []),
          ];
          return `    { ${parts.join(', ')} },`;
        })
        .join('\n');
      return `  // <${e.selector}>\n  ${klass}: [\n${rows}\n  ],`;
    })
    .join('\n');

  return `/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/* eslint-disable */
/**
 * GENERATED by \`pnpm gen:api-docs\` from the library's JSDoc — do not edit.
 *
 * Fix a description, a type or a default in \`projects/lib\` and re-run; the docs
 * follow. A page consumes this as \`API.WrFoo\` instead of keeping a second copy.
 */

import type { DocApiRow } from '#core/components';

/**
 * \`satisfies\` rather than a \`Record<string, …>\` annotation, deliberately: the
 * keys stay literal, so \`API.WrButton\` type-checks and \`API.WrButtno\` is a
 * compile error instead of \`undefined\` at runtime.
 */
export const API = {
${body}
} satisfies Record<string, readonly DocApiRow[]>;
`;
}

/** Hand-written `api` arrays still living in showcase pages, keyed by file. */
function handWritten(): Map<string, string> {
  const found = new Map<string, string>();
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, name.name);
      if (name.isDirectory()) {
        if (name.name !== 'generated') walk(full);
      } else if (name.name.endsWith('.ts')) {
        const src = readFileSync(full, 'utf8');
        if (/readonly api\s*:\s*readonly DocApiRow\[\]\s*=\s*\[/.test(src)) found.set(full, src);
      }
    }
  };
  walk(PAGES_ROOT);
  return found;
}

/** `…/reference/components/button/button.ts` → `button`. */
function entryOf(file: string): string {
  const parts = relative(PAGES_ROOT, file).split('/');
  return parts[parts.length - 2] ?? '';
}

function check(api: Map<string, ApiEntry>): number {
  // The primary class of an entry point is the one named after the folder —
  // `button/` → `WrButton`. Matching on selector fails here, because the button's
  // selector is `wr-btn` while `wr-button-group` looks like a folder match.
  const pascal = (entry: string): string =>
    `Wr${entry
      .split('-')
      .map(p => p.charAt(0).toUpperCase() + p.slice(1))
      .join('')}`;

  const byEntry = new Map<string, ApiEntry>();
  for (const e of api.values()) {
    if (e.klass === pascal(e.entry)) byEntry.set(e.entry, e);
    else if (!byEntry.has(e.entry)) byEntry.set(e.entry, e);
  }

  let mismatched = 0;
  let unmapped = 0;

  for (const [file, src] of handWritten()) {
    const entry = entryOf(file);
    const found = byEntry.get(entry);
    if (!found) {
      unmapped++;
      continue;
    }

    // Pages legitimately document things that are not inputs of this component:
    // interface shapes (`WrAnchorLink`, `label`), CSS custom properties, sibling
    // selectors (`<wr-card-header>`, `[wrTilt]`) and methods. Only rows that
    // look like a plain member name are comparable.
    const isMember = (n: string): boolean =>
      /^\(?[a-z][A-Za-z0-9]*\)?$/.test(n) && !n.includes('(') === !n.endsWith(')');

    const documented = new Set(
      [...src.matchAll(/name:\s*'([^']+)'/g)].map(m => m[1] ?? '').filter(n => /^\(?[a-z][A-Za-z0-9]*\)?$/.test(n))
    );
    const actual = new Set(found.rows.map(r => r.name).filter(isMember));

    const missing = [...actual].filter(n => !documented.has(n) && !documented.has(n.replace(/[()]/g, '')));
    const stale = [...documented].filter(n => !actual.has(n) && !actual.has(`(${n})`));

    if (missing.length === 0 && stale.length === 0) continue;
    mismatched++;
    console.log(`  ${relative(ROOT_PATH, file)}  (${found.klass})`);
    if (missing.length) console.log(`      missing:  ${missing.join(', ')}`);
    if (stale.length) console.log(`      unknown:  ${stale.join(', ')}`);
  }

  console.log(
    `\n  ${mismatched} page(s) disagree with the source; ${unmapped} not mapped to an entry point (interfaces, guides, groups).`
  );
  return mismatched;
}

function main(): void {
  const api = extractApi();
  const mode = process.argv.includes('--check') ? 'check' : 'write';

  if (mode === 'check') {
    console.log(`Comparing hand-written API tables against ${api.size} extracted classes\n`);
    // Reporting only for now — the generated data is the fix, and pages migrate
    // to it one at a time. Flip to a non-zero exit once the count reaches zero.
    check(api);
    process.exit(0);
  }

  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, serialize(api));
  const rows = [...api.values()].reduce((n, e) => n + e.rows.length, 0);
  console.log(`✓ ${relative(ROOT_PATH, OUT_FILE)} — ${api.size} classes, ${rows} rows`);
}

main();
