/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/**
 * Writes `projects/showcase/app/_core/generated/selectors.ts` — the
 * `selector part → { symbol, path }` map the docs site resolves a template
 * fragment against, so a snippet showing `<wr-select>` can name the imports it
 * needs without a hand-kept table going stale beside it.
 *
 *   pnpm gen:selectors
 *
 * Runs as the first step of `build:showcase`, and the output is committed so a
 * clean checkout type-checks before anything is generated.
 *
 * The scan lives in `scripts/lib/build-selector-map.ts` — read its header
 * before changing anything here; the completeness assertion and the
 * comment-aware brace matcher are both load-bearing and both were paid for.
 */

import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

import { buildSelectorMap, type WrSelectorMap, type WrSelectorTarget } from './lib/build-selector-map';
import { ROOT_PATH } from './lib/paths/root';

const OUT_DIR = resolve(ROOT_PATH, 'projects/showcase/app/_core/generated');
const OUT_FILE = join(OUT_DIR, 'selectors.ts');

const LIB_ROOT = resolve(ROOT_PATH, 'projects/lib');

/**
 * Entry points that actually ship a stylesheet, as `ngwr/<name>` subpaths.
 *
 * The sandbox needs this to write `@use 'ngwr/button';` instead of the umbrella
 * `@use 'ngwr';`, and it cannot guess: `@use` on an entry point with no
 * `styles/_index.scss` — `ngwr/date`, `ngwr/utils`, every `<name>/testing` — is
 * a build error, while the umbrella compiles all hundred-and-twenty component
 * sheets whether the demo draws one component or all of them. Reading the
 * filesystem is the only honest source; a hand-kept list would drift the first
 * time an entry point grew or lost styles.
 */
function styleEntryPoints(dir = LIB_ROOT, prefix = ''): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    if (name.startsWith('.') || name === 'node_modules' || name === 'testing') continue;
    const full = resolve(dir, name);
    try {
      if (!statSync(full).isDirectory()) continue;
    } catch {
      continue;
    }
    const entry = prefix ? `${prefix}/${name}` : name;
    if (existsSync(join(full, 'styles', '_index.scss'))) out.push(`ngwr/${entry}`);
    out.push(...styleEntryPoints(full, entry));
  }
  return out.sort();
}

function bucket(entries: Record<string, WrSelectorTarget>): string {
  return Object.entries(entries)
    .map(([key, t]) => `    ${JSON.stringify(key)}: { symbol: ${JSON.stringify(t.symbol)}, path: ${JSON.stringify(t.path)} },`)
    .join('\n');
}

function serialize(map: WrSelectorMap, styles: readonly string[]): string {
  return `/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/* eslint-disable */
/**
 * GENERATED by \`pnpm gen:selectors\` from the library's \`@Component\` /
 * \`@Directive\` selectors — do not edit.
 *
 * Rename a selector in \`projects/lib\` and re-run; this follows. Missing an
 * entry means the class is not exported from any \`public-api.ts\` — fix it
 * there, not here. The scan is \`scripts/lib/build-selector-map.ts\`.
 *
 * ${map.stats.mapped} of ${map.stats.declarations} declarations are mapped: ${map.stats.withoutSelector} carry no selector and
 * ${map.stats.internal} are internal classes no entry point publishes. A deliberate subset,
 * not a lossy one — the generator throws rather than skipping what it cannot read.
 */

/** Where a selector part resolves to: the class, and the subpath to import it from. */
export interface SelectorRef {
  readonly symbol: string;
  readonly path: string;
}

/**
 * \`satisfies\` rather than a \`Record<string, …>\` annotation, deliberately: the
 * keys stay literal, so \`SELECTORS.tags['wr-btn']\` type-checks and a typo is a
 * compile error instead of \`undefined\` at runtime.
 *
 * A name can appear in BOTH buckets — \`wr-btn\` is the element \`<wr-btn>\` and
 * the attribute in \`button[wr-btn]\`, one class either way.
 */
export const SELECTORS = {
  /** Element selectors, without the angle brackets: \`wr-alert\`. */
  tags: {
${bucket(map.tags)}
  },
  /** Attribute selectors, without the square brackets: \`wrInput\`. */
  attributes: {
${bucket(map.attributes)}
  },
} satisfies {
  readonly tags: Record<string, SelectorRef>;
  readonly attributes: Record<string, SelectorRef>;
};

/**
 * Every \`ngwr/*\` subpath that ships a stylesheet, so a generated project can
 * \`@use\` exactly the components it renders. \`@use\` on an entry point without
 * one does not fail quietly — it fails the build.
 */
export const STYLE_ENTRY_POINTS: readonly string[] = [
${styles.map(p => `  ${JSON.stringify(p)},`).join('\n')}
];
`;
}

function main(): void {
  const map = buildSelectorMap();
  const { stats } = map;

  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
  const styles = styleEntryPoints();
  writeFileSync(OUT_FILE, serialize(map, styles));

  console.log(
    `✓ ${relative(ROOT_PATH, OUT_FILE)} — ${Object.keys(map.tags).length} tags, ` +
      `${Object.keys(map.attributes).length} attributes from ${stats.mapped} declarations, ` +
      `${styles.length} style entry points`
  );
  console.log(
    `  ${stats.files} files, ${stats.declarations} declarations` +
      `${stats.mentions > 0 ? ` (+${stats.mentions} mentioned in comments or strings)` : ''}: ` +
      `${stats.mapped} mapped, ${stats.withoutSelector} with no selector, ${stats.internal} internal.`
  );
  if (stats.internal > 0) {
    // Printed in full rather than counted: an internal class here is a decision
    // ("nothing outside the library writes `<wr-mention-panel>`"), and a reader
    // can only check it against the catalog if the names are on screen.
    console.log(`  Internal (not exported from any public-api.ts): ${stats.internalClasses.join(', ')}`);
  }
}

main();
