/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/**
 * Writes `projects/showcase/app/_core/generated/css-vars.ts` — the per-component
 * `--wr-*` hooks each reference page publishes, keyed by the page's route.
 *
 *   pnpm gen:css-vars          rewrite the file
 *   pnpm check:css-vars        fail if the committed file is stale
 *
 * Runs as a step of `build:showcase`, beside `gen:selectors` and `gen:quality`,
 * and the output is committed so a clean checkout type-checks before anything is
 * generated.
 *
 * Why the docs need it: the global token layer is catalogued across six
 * `/guides/tokens/*` pages and the ~380 component-scoped properties beside it
 * were catalogued nowhere, so restyling a component the sanctioned way meant
 * reading `node_modules/ngwr/<name>/styles/_index.scss` to find out what exists.
 * A consumer who cannot find a hook overrides the internal BEM class instead —
 * and those class names are published as stable, so the missing catalogue
 * converts straight into a maintenance obligation nobody agreed to take.
 *
 * The scan lives in `scripts/lib/build-css-var-map.ts`; read its header before
 * changing anything here. This file only decides which PAGE shows what, and
 * there is one rule: a page's directory name is its entry point's directory
 * name. `reference/components/button-group` and `reference/components/form-field`
 * name no entry point and get no section — correctly, since neither
 * `.wr-btn-group` nor `.wr-form-field` publishes a hook of its own.
 *
 * A component whose page cannot be found is REPORTED rather than dropped
 * silently, and rather than thrown over: `check:api-docs` already fails on an
 * entry point with public members and no page, so a second gate saying the same
 * thing would only make one failure look like two.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

import { buildCssVarMap, type WrCssVarEntry, type WrCssVarMap } from './lib/build-css-var-map';
import { ROOT_PATH } from './lib/paths/root';

const OUT_DIR = resolve(ROOT_PATH, 'projects/showcase/app/_core/generated');
const OUT_FILE = join(OUT_DIR, 'css-vars.ts');
const APP_ROOT = resolve(ROOT_PATH, 'projects/showcase/app');

/**
 * Where a page for an entry point may live, most specific first.
 *
 * `keyboard` has both `reference/components/keyboard` and `guides/keyboard`, and
 * the component page is the one that documents the component — so the order is
 * the tie-break, and `guides/` is deliberately absent from the list: a guide is
 * prose about a topic, not the reference page for an entry point.
 */
const CLUSTERS = [
  'reference/components',
  'animations',
  'reference/services',
  'reference/directives',
  'reference/pipes',
] as const;

/** `alert` → `reference/components/alert`, or `null` when no page documents it. */
function routeOf(entry: string): string | null {
  for (const cluster of CLUSTERS) {
    const route = `${cluster}/${entry}`;
    if (existsSync(join(APP_ROOT, route))) return route;
  }
  return null;
}

function rows(entry: WrCssVarEntry): string {
  return entry.vars
    .map(v => {
      const parts = [
        `name: ${JSON.stringify(v.name)}`,
        `default: ${JSON.stringify(v.value)}`,
        `scope: ${JSON.stringify(v.scope)}`,
      ];
      if (!v.base) parts.push('base: false');
      if (v.overrides > 0) parts.push(`overrides: ${v.overrides}`);
      return `      { ${parts.join(', ')} },`;
    })
    .join('\n');
}

function serialize(map: WrCssVarMap, byRoute: ReadonlyMap<string, WrCssVarEntry>): string {
  const blocks = [...byRoute]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([route, entry]) => {
      return `  ${JSON.stringify(route)}: {
    subpath: ${JSON.stringify(entry.subpath)},
    vars: [
${rows(entry)}
    ],
  },`;
    })
    .join('\n');

  return `/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/* eslint-disable */
/**
 * GENERATED by \`pnpm gen:css-vars\` from the library's stylesheets — do not edit.
 *
 * The \`--wr-*\` hooks each component publishes, keyed by the route of the page
 * that shows them. Rename a hook or retune a default in \`projects/lib\` and
 * re-run; this follows. The scan is \`scripts/lib/build-css-var-map.ts\`.
 *
 * ${map.total} hook(s) across ${byRoute.size} page(s). A property is here only when the
 * library READS it — a hook nothing reads is reported by the generator as a
 * finding rather than listed as a knob — and only when the component that
 * declares it also owns it: ${map.delegated} declaration(s) are one component setting
 * another's hook (\`--wr-icon-size\` inside its own \`<wr-icon>\`) and belong on
 * the owner's page, not on the setter's.
 */

import type { DocCssVarRow } from '#core/components';

/** One page's hooks, and the subpath whose stylesheet declares them. */
export interface DocCssVars {
  readonly subpath: string;
  readonly vars: readonly DocCssVarRow[];
}

/**
 * \`satisfies\` rather than a \`Record<string, …>\` annotation, deliberately: the
 * keys stay literal, which is what makes {@link DocCssVarRoute} a union of the
 * routes that really exist instead of \`string\`. The lookup is by a URL the
 * router hands over at runtime, so it is guarded rather than typed — but the
 * cast it needs can only name a route this file still carries.
 */
export const CSS_VARS = {
${blocks}
} satisfies Record<string, DocCssVars>;

/** Route keys, as a set the page shell can probe without widening the type above. */
export type DocCssVarRoute = keyof typeof CSS_VARS;
`;
}

function main(): void {
  const check = process.argv.includes('--check');
  const map = buildCssVarMap();

  const byRoute = new Map<string, WrCssVarEntry>();
  const homeless: string[] = [];
  for (const entry of map.entries) {
    const route = routeOf(entry.entry);
    if (route) byRoute.set(route, entry);
    else homeless.push(`${entry.subpath} (${entry.vars.length} hook(s))`);
  }

  const next = serialize(map, byRoute);
  const path = relative(ROOT_PATH, OUT_FILE);

  if (check) {
    const current = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, 'utf8') : '';
    if (current !== next) {
      console.error(`\n✘ ${path} is out of date with projects/lib. Run \`pnpm gen:css-vars\` and commit the result.\n`);
      process.exit(1);
    }
    console.log(`✓ ${path} — ${map.total} hook(s) across ${byRoute.size} page(s), up to date`);
  } else {
    if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
    writeFileSync(OUT_FILE, next);
    console.log(`✓ ${path} — ${map.total} hook(s) across ${byRoute.size} page(s)`);
  }

  console.log(
    `  ${map.entries.length} entry point(s) publish one; ${map.delegated} declaration(s) filed under the hook's owner.`
  );

  if (homeless.length > 0) {
    console.log(`  No reference page to show them on: ${homeless.join(', ')}`);
  }

  if (map.orphans.length > 0) {
    // Printed in full rather than counted, for the reason `check:tokens` gives
    // about the theme layer: a hook nothing reads is not automatically a bug —
    // `--wr-density-text` and `--wr-density-gap` are published for consumers to
    // read in their own `calc()`, which is exactly the case that has to stay
    // visible instead of being tidied into a number.
    console.log(`  Declared and never read (not listed, ${map.orphans.length}):`);
    for (const { name, where } of map.orphans) console.log(`    ${name}  ${where}`);
  }
}

main();
