/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/**
 * Projects the library's signal API into the showcase as generated data, and
 * reports where a hand-written docs table still disagrees with the source.
 *
 * Two modes:
 *
 *   pnpm gen:api-docs          write projects/showcase/app/_core/generated/api.ts
 *   pnpm check:api-docs        compare hand-written tables against the source
 *
 * The check is the half that pays immediately: it turns "the docs drifted" from
 * something a human notices months later into a failing build. The 2026-08-07
 * audit found `skeleton` and `fuzzy-text` documenting defaults the code did not
 * have, `switch` missing its primary two-way model, `select` still listing an
 * input removed a major earlier, and four pages with no input table at all — all
 * of it invisible to every existing gate.
 *
 * Pages opt in to the generated data by replacing their hand-written array with
 * `API['WrFoo']`. Until a page does, the check keeps it honest.
 */

import { readFileSync, readdirSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

import { type ApiEntry, type ApiRow, extractApi } from './lib/extract-api';
import { ROOT_PATH } from './lib/paths/root';

const OUT_DIR = resolve(ROOT_PATH, 'projects/showcase/app/_core/generated');
const OUT_FILE = join(OUT_DIR, 'api.ts');
const PAGES_ROOT = resolve(ROOT_PATH, 'projects/showcase/app');

function serialize(api: Map<string, ApiEntry>): string {
  const entries = [...api.entries()].sort(([a], [b]) => a.localeCompare(b));

  const body = entries
    .map(([klass, e]) => {
      const rows = e.rows
        .map(r => {
          const parts = [
            `name: ${JSON.stringify(r.name)}`,
            `description: ${JSON.stringify(r.description)}`,
            `type: ${JSON.stringify(r.type)}`,
            ...(r.required ? ['required: true'] : []),
            ...(r.default !== undefined ? [`default: ${JSON.stringify(r.default)}`] : []),
          ];
          return `    { ${parts.join(', ')} },`;
        })
        .join('\n');
      return `  // <${e.selector}>\n  ${klass}: [\n${rows}\n  ],`;
    })
    .join('\n');

  return `/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/* eslint-disable */
/**
 * GENERATED by \`pnpm gen:api-docs\` from the library's JSDoc — do not edit.
 *
 * Fix a description, a type or a default in \`projects/lib\` and re-run; the docs
 * follow. A page consumes this as \`API.WrFoo\` instead of keeping a second copy.
 */

import type { DocApiRow } from '#core/components';

/**
 * \`satisfies\` rather than a \`Record<string, …>\` annotation, deliberately: the
 * keys stay literal, so \`API.WrButton\` type-checks and \`API.WrButtno\` is a
 * compile error instead of \`undefined\` at runtime.
 */
export const API = {
${body}
} satisfies Record<string, readonly DocApiRow[]>;
`;
}

/** Hand-written `api` arrays still living in showcase pages, keyed by file. */
function handWritten(): Map<string, string> {
  const found = new Map<string, string>();
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, name.name);
      if (name.isDirectory()) {
        if (name.name !== 'generated') walk(full);
      } else if (name.name.endsWith('.ts')) {
        const src = readFileSync(full, 'utf8');
        if (/readonly api\s*:\s*readonly DocApiRow\[\]\s*=\s*\[/.test(src)) found.set(full, src);
      }
    }
  };
  walk(PAGES_ROOT);
  return found;
}

/** `…/reference/components/button/button.ts` → `button`. */
function entryOf(file: string): string {
  const parts = relative(PAGES_ROOT, file).split('/');
  return parts[parts.length - 2] ?? '';
}

/**
 * `[wrSpotlight].resetX` / `(touch)` / `[wrTilt]` / `.resetY` → `resetX` /
 * `touch` / `wrTilt` / `resetY`. Pages write a member several ways; the
 * comparison happens on the bare identifier.
 */
function bare(name: string): string {
  return name
    .replace(/^\[[A-Za-z]+\]\./, '')
    // Repeated, not once: `[(position)]` is a banana-in-a-box, two layers deep.
    .replace(/^[[(]+/, '')
    .replace(/[\])]+$/, '')
    .replace(/^\./, '');
}

function isMember(name: string): boolean {
  return /^(?:\[[A-Za-z]+\]\.)?[[(.]{0,2}[a-z][A-Za-z0-9]*[\])]{0,2}$/.test(name);
}

/**
 * Member names a page documents, from every table on it.
 *
 * Two shapes have to be handled or the report fills with noise.
 *
 * `sub: true` marks a row indented under the one above it, and what that means
 * depends entirely on the parent: under `<wr-list>` the sub-rows are the
 * component's inputs, under `WrMarqueeImage` they are fields of an interface,
 * and under `variant` they are the allowed values of that one input. Only the
 * first kind is a member, so the parent row decides.
 *
 * And one row often covers two members (`text / texts`,
 * `[wrSpotlight].resetX / .resetY`), which reads as both of them undocumented
 * unless the slash is split.
 */
function documentedMembers(src: string): string[] {
  // Split on the name rather than matching a whole `{…}` row: a description can
  // contain braces, and a row regex that assumes it cannot silently drops the
  // row — which then reads as an undocumented member.
  const parts = src.split(/name:\s*'([^']+)'/);
  const out: string[] = [];
  let parent = '';

  for (let i = 1; i < parts.length; i += 2) {
    const raw = parts[i] ?? '';
    const tail = (parts[i + 1] ?? '').split('},')[0] ?? '';
    const sub = /\bsub:\s*true/.test(tail);

    if (!sub) {
      // `<wr-list>` headings fail `isMember` on their own; `[wrAffixOffsetTop]`
      // passes it, and should — bracket form is how a page writes an input.
      parent = raw;
    } else if (!/^<wr-[a-z-]+>$|^\[wr[A-Za-z]+\]$/.test(parent)) {
      // Indented under a type or under another input — an interface field or an
      // allowed value, not a member.
      continue;
    }

    for (const piece of raw.split('/')) {
      const name = piece.trim();
      if (isMember(name)) out.push(name);
    }
  }

  return out;
}

function check(api: Map<string, ApiEntry>): number {
  // An entry point is compared as a whole, not class by class: `layout/`
  // documents `WrLayout` + header + sider + content + footer on one page, and
  // `table/` documents the column and cell directives alongside the table. The
  // page's own tables are one flat pool of names, so the source side has to be
  // one too, or every sibling directive reads as undocumented drift.
  const byEntry = new Map<string, { readonly primary: string; readonly rows: ApiRow[] }>();
  const pascal = (entry: string): string =>
    `Wr${entry
      .split('-')
      .map(p => p.charAt(0).toUpperCase() + p.slice(1))
      .join('')}`;

  for (const e of api.values()) {
    const found = byEntry.get(e.entry);
    if (!found) {
      byEntry.set(e.entry, { primary: e.klass, rows: [...e.rows] });
      continue;
    }
    found.rows.push(...e.rows);
    // The class named after the folder is the page's headline, whatever order
    // the files were walked in.
    if (e.klass === pascal(e.entry)) byEntry.set(e.entry, { primary: e.klass, rows: found.rows });
  }

  let mismatched = 0;
  let unmapped = 0;

  for (const [file, src] of handWritten()) {
    const entry = entryOf(file);
    const found = byEntry.get(entry);
    if (!found) {
      unmapped++;
      continue;
    }

    const names = documentedMembers(src);
    const actual = new Set(found.rows.map(r => r.name).filter(isMember).map(bare));

    // A member counts as documented however the page writes it. But only a name
    // written BARE is held to existing: `[wrTilt]` in brackets is template
    // syntax, and pages use it to document the directive's own selector, which
    // is not a member of anything.
    const documented = new Set(names.map(bare));
    const missing = [...actual].filter(n => !documented.has(n));
    const stale = [...new Set(names.filter(n => !n.startsWith('[') && !actual.has(bare(n))).map(bare))];

    if (missing.length === 0 && stale.length === 0) continue;
    mismatched++;
    console.log(`  ${relative(ROOT_PATH, file)}  (${found.primary})`);
    if (missing.length) console.log(`      missing:  ${missing.join(', ')}`);
    if (stale.length) console.log(`      unknown:  ${stale.join(', ')}`);
  }

  console.log(
    `\n  ${mismatched} page(s) disagree with the source; ${unmapped} not mapped to an entry point (interfaces, guides, groups).`
  );
  return mismatched;
}

function main(): void {
  const api = extractApi();
  const mode = process.argv.includes('--check') ? 'check' : 'write';

  if (mode === 'check') {
    console.log(`Comparing hand-written API tables against ${api.size} extracted classes\n`);
    // Reporting only for now — the generated data is the fix, and pages migrate
    // to it one at a time. Flip to a non-zero exit once the count reaches zero.
    check(api);
    process.exit(0);
  }

  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, serialize(api));
  const rows = [...api.values()].reduce((n, e) => n + e.rows.length, 0);
  console.log(`✓ ${relative(ROOT_PATH, OUT_FILE)} — ${api.size} classes, ${rows} rows`);
}

main();
