/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/**
 * Writes `projects/showcase/app/_core/generated/selectors.ts` — the
 * `selector part → { symbol, path }` map the docs site resolves a template
 * fragment against, so a snippet showing `<wr-select>` can name the imports it
 * needs without a hand-kept table going stale beside it.
 *
 *   pnpm gen:selectors
 *
 * Runs as the first step of `build:showcase`, and the output is committed so a
 * clean checkout type-checks before anything is generated.
 *
 * The scan lives in `scripts/lib/build-selector-map.ts` — read its header
 * before changing anything here; the completeness assertion and the
 * comment-aware brace matcher are both load-bearing and both were paid for.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

import { buildSelectorMap, type WrSelectorMap, type WrSelectorTarget } from './lib/build-selector-map';
import { ROOT_PATH } from './lib/paths/root';

const OUT_DIR = resolve(ROOT_PATH, 'projects/showcase/app/_core/generated');
const OUT_FILE = join(OUT_DIR, 'selectors.ts');

function bucket(entries: Record<string, WrSelectorTarget>): string {
  return Object.entries(entries)
    .map(([key, t]) => `    ${JSON.stringify(key)}: { symbol: ${JSON.stringify(t.symbol)}, path: ${JSON.stringify(t.path)} },`)
    .join('\n');
}

function serialize(map: WrSelectorMap): string {
  return `/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */

/* eslint-disable */
/**
 * GENERATED by \`pnpm gen:selectors\` from the library's \`@Component\` /
 * \`@Directive\` selectors — do not edit.
 *
 * Rename a selector in \`projects/lib\` and re-run; this follows. Missing an
 * entry means the class is not exported from any \`public-api.ts\` — fix it
 * there, not here. The scan is \`scripts/lib/build-selector-map.ts\`.
 *
 * ${map.stats.mapped} of ${map.stats.declarations} declarations are mapped: ${map.stats.withoutSelector} carry no selector and
 * ${map.stats.internal} are internal classes no entry point publishes. A deliberate subset,
 * not a lossy one — the generator throws rather than skipping what it cannot read.
 */

/** Where a selector part resolves to: the class, and the subpath to import it from. */
export interface SelectorRef {
  readonly symbol: string;
  readonly path: string;
}

/**
 * \`satisfies\` rather than a \`Record<string, …>\` annotation, deliberately: the
 * keys stay literal, so \`SELECTORS.tags['wr-btn']\` type-checks and a typo is a
 * compile error instead of \`undefined\` at runtime.
 *
 * A name can appear in BOTH buckets — \`wr-btn\` is the element \`<wr-btn>\` and
 * the attribute in \`button[wr-btn]\`, one class either way.
 */
export const SELECTORS = {
  /** Element selectors, without the angle brackets: \`wr-alert\`. */
  tags: {
${bucket(map.tags)}
  },
  /** Attribute selectors, without the square brackets: \`wrInput\`. */
  attributes: {
${bucket(map.attributes)}
  },
} satisfies {
  readonly tags: Record<string, SelectorRef>;
  readonly attributes: Record<string, SelectorRef>;
};
`;
}

function main(): void {
  const map = buildSelectorMap();
  const { stats } = map;

  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, serialize(map));

  console.log(
    `✓ ${relative(ROOT_PATH, OUT_FILE)} — ${Object.keys(map.tags).length} tags, ` +
      `${Object.keys(map.attributes).length} attributes from ${stats.mapped} declarations`
  );
  console.log(
    `  ${stats.files} files, ${stats.declarations} declarations` +
      `${stats.mentions > 0 ? ` (+${stats.mentions} mentioned in comments or strings)` : ''}: ` +
      `${stats.mapped} mapped, ${stats.withoutSelector} with no selector, ${stats.internal} internal.`
  );
  if (stats.internal > 0) {
    // Printed in full rather than counted: an internal class here is a decision
    // ("nothing outside the library writes `<wr-mention-panel>`"), and a reader
    // can only check it against the catalog if the names are on screen.
    console.log(`  Internal (not exported from any public-api.ts): ${stats.internalClasses.join(', ')}`);
  }
}

main();
