/**
 * Generates TypeScript icon constants from SVG files.
 *
 * Replaces @angular-extensions/svg-icons-builder with a standalone script.
 *
 * Usage:
 *   pnpm tsx scripts/generate-icons.ts
 *
 * Input:  projects/lib/icon/_svg/*.svg
 * Output: projects/lib/icon/icons.ts
 */

import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';

import { type Config, optimize } from 'svgo';

// Config
const ROOT = resolve(__dirname, '..');
const SVG_DIR = join(ROOT, 'projects/lib/icon/_svg');
const ICONS_DIR = join(ROOT, 'projects/lib/icon/icons');
const TYPES_DIR = join(ROOT, 'projects/lib/icon/types');

const LICENSE = `/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */
`;

const AUTOGEN = `// This file is auto-generated by scripts/generate-icons.ts\n// Do not edit manually.\n`;

const SVGO_CONFIG = {
  plugins: [
    'preset-default',
    'convertStyleToAttrs',
    { name: 'addClassesToSVGElement', params: { className: 'wr-icon__svg' } },
    {
      name: 'convertColors',
      params: {
        currentColor: true,
        names2hex: false,
        rgb2hex: false,
        shorthex: false,
        shortname: false,
      },
    },
  ],
} satisfies Config;

// Types

type Icon = { kebab: string; camel: string; svg: string };

// Helpers

/** 'logo-github.svg' → 'logo-github' */
function svgToKebab(filename: string): string {
  return basename(filename, '.svg');
}

/** 'logo-github' → 'logoGithub' */
function kebabToCamel(name: string): string {
  return name.replace(/-([a-z\d])/g, (_, char: string) => char.toUpperCase());
}

function optimizeSvg(raw: string): string {
  const result = optimize(raw, SVGO_CONFIG);
  return result.data
    .replace(/\n/g, '')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

function collectIcons(): Icon[] {
  return readdirSync(SVG_DIR)
    .filter(f => f.endsWith('.svg'))
    .sort()
    .map(file => {
      const raw = readFileSync(join(SVG_DIR, file), 'utf-8');
      const kebab = svgToKebab(file);
      return { kebab, camel: kebabToCamel(kebab), svg: optimizeSvg(raw) };
    });
}

function writeIconNameType(icons: Icon[]): void {
  const names = icons.map(i => `  | '${i.kebab}'`).join('\n');

  const content = `${LICENSE}\n${AUTOGEN}
/**
 * Name of a built-in icon shipped with the library.
 *
 * Use this type when you want to restrict a value to the built-in set only.
 */
export type WrBuiltInIconName =
${names};

/**
 * Any icon name — either a built-in shipped with the library
 * or a custom one registered via {@link provideWrIcons}.
 *
 * The \`string & {}\` intersection preserves autocomplete for
 * built-in names while accepting any custom string.
 */
// eslint-disable-next-line @typescript-eslint/no-redundant-type-constituents
export type WrIconName = WrBuiltInIconName | (string & {});
`;

  writeFileSync(join(TYPES_DIR, 'icon-name.ts'), content, 'utf-8');
}

function writeIconFile(icon: Icon): void {
  const content =
    `${LICENSE}\nimport type { WrIcon } from '../types';\n\n` +
    `export const ${icon.camel}: WrIcon = {\n` +
    `  name: '${icon.kebab}',\n` +
    `  data: '${icon.svg.replace(/'/g, "\\'")}',\n` +
    `};\n`;

  writeFileSync(join(ICONS_DIR, `${icon.kebab}.ts`), content, 'utf-8');
}

function writeIconsIndex(icons: Icon[]): void {
  const exports = icons.map(i => `export { ${i.camel} } from './${i.kebab}';`).join('\n');
  const imports = icons.map(i => `import { ${i.camel} } from './${i.kebab}';`).join('\n');
  const all = icons.map(i => i.camel).join(', ');

  const content =
    `${AUTOGEN}\n${exports}\n\n${imports}\n\n` +
    `import type { WrIcon } from '../types';\n\n` +
    `/**\n` +
    ` * Complete set of built-in icons.\n` +
    ` *\n` +
    ` * Importing this pulls every icon into the bundle — prefer importing\n` +
    ` * individual icons by name for tree-shaking. Use \`wrIconSet\` only for\n` +
    ` * icon pickers, documentation pages, or similar exhaustive listings.\n` +
    ` */\n` +
    `export const wrIconSet: WrIcon[] = [${all}];\n`;

  writeFileSync(join(ICONS_DIR, 'index.ts'), content, 'utf-8');
}

// Run

rmSync(ICONS_DIR, { recursive: true, force: true });
mkdirSync(ICONS_DIR, { recursive: true });
mkdirSync(TYPES_DIR, { recursive: true });

const icons = collectIcons();

writeIconNameType(icons);
for (const icon of icons) writeIconFile(icon);
writeIconsIndex(icons);

console.log(`Generated ${icons.length} icons → ${ICONS_DIR}`);
