/**
 * Generates TypeScript icon constants from SVG files.
 *
 * Replaces @angular-extensions/svg-icons-builder with a standalone script.
 *
 * Usage:
 *   pnpm tsx scripts/generate-icons.ts
 *
 * Inputs:
 *   - projects/lib/icon/_svg/*.svg     — icon sources
 *   - projects/lib/icon/_svg/_tags.json — { [kebab]: string[] } search tags (showcase only)
 *
 * Outputs:
 *   - projects/lib/icon/icons/*.ts                              — pure icon data (lib bundle)
 *   - projects/lib/icon/types/icon-name.ts                      — name union (lib bundle)
 *   - projects/showcase/app/docs/components/icon/_data/icon-tags.generated.ts
 *                                                               — search tags (showcase only)
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { type Config, optimize } from 'svgo';

// Config
const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const SVG_DIR = join(ROOT, 'projects/lib/icon/_svg');
const TAGS_FILE = join(SVG_DIR, '_tags.json');
const ICONS_DIR = join(ROOT, 'projects/lib/icon/icons');
const TYPES_DIR = join(ROOT, 'projects/lib/icon/types');
const SHOWCASE_DATA_DIR = join(ROOT, 'projects/showcase/app/docs/components/icon/_data');
const SHOWCASE_TAGS_FILE = join(SHOWCASE_DATA_DIR, 'icon-tags.generated.ts');

const LICENSE = `/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/thekhegay/ngwr/blob/main/LICENSE
 */
`;

const AUTOGEN = `// This file is auto-generated by scripts/generate-icons.ts\n// Do not edit manually.\n`;

const SVGO_CONFIG = {
  plugins: [
    'preset-default',
    'convertStyleToAttrs',
    { name: 'addClassesToSVGElement', params: { className: 'wr-icon__svg' } },
    {
      name: 'convertColors',
      params: {
        currentColor: true,
        names2hex: false,
        rgb2hex: false,
        shorthex: false,
        shortname: false,
      },
    },
  ],
} satisfies Config;

// Types

type Icon = { kebab: string; camel: string; svg: string };

// Helpers

/** 'logo-github.svg' → 'logo-github' */
function svgToKebab(filename: string): string {
  return basename(filename, '.svg');
}

/** 'logo-github' → 'logoGithub' */
function kebabToCamel(name: string): string {
  return name.replace(/-([a-z\d])/g, (_, char: string) => char.toUpperCase());
}

function optimizeSvg(raw: string): string {
  const result = optimize(raw, SVGO_CONFIG);
  return result.data
    .replace(/\n/g, '')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

function collectIcons(): Icon[] {
  return readdirSync(SVG_DIR)
    .filter(f => f.endsWith('.svg'))
    .sort()
    .map(file => {
      const raw = readFileSync(join(SVG_DIR, file), 'utf-8');
      const kebab = svgToKebab(file);
      return { kebab, camel: kebabToCamel(kebab), svg: optimizeSvg(raw) };
    });
}

function writeIconNameType(icons: Icon[]): void {
  const names = icons.map(i => `  | '${i.kebab}'`).join('\n');

  const content = `${LICENSE}\n${AUTOGEN}
/**
 * Name of a built-in icon shipped with the library.
 *
 * Use this type when you want to restrict a value to the built-in set only.
 */
export type WrBuiltInIconName =
${names};

/**
 * Any icon name — either a built-in shipped with the library
 * or a custom one registered via {@link provideWrIcons}.
 *
 * The \`string & {}\` intersection preserves autocomplete for
 * built-in names while accepting any custom string.
 */
export type WrIconName = WrBuiltInIconName | (string & {});
`;

  writeFileSync(join(TYPES_DIR, 'icon-name.ts'), content, 'utf-8');
}

function writeIconFile(icon: Icon): void {
  const content =
    `${LICENSE}\nimport type { WrIcon } from '../types';\n\n` +
    `export const ${icon.camel}: WrIcon = {\n` +
    `  name: '${icon.kebab}',\n` +
    `  data: '${icon.svg.replace(/'/g, "\\'")}',\n` +
    `};\n`;

  writeFileSync(join(ICONS_DIR, `${icon.kebab}.ts`), content, 'utf-8');
}

function readTags(): Record<string, string[]> {
  if (!existsSync(TAGS_FILE)) {
    process.stderr.write(`[icons] _tags.json not found at ${TAGS_FILE} — emitting empty tag map.\n`);
    return {};
  }
  const raw = readFileSync(TAGS_FILE, 'utf-8');
  return JSON.parse(raw) as Record<string, string[]>;
}

function writeShowcaseTags(icons: Icon[], tags: Record<string, string[]>): void {
  const known = new Set(icons.map(i => i.kebab));

  // Warn on stale entries
  for (const key of Object.keys(tags)) {
    if (!known.has(key)) {
      process.stderr.write(`[icons] _tags.json: '${key}' has no matching SVG — entry will be dropped.\n`);
    }
  }

  // Warn on icons missing tags
  const missing = icons.filter(i => !tags[i.kebab]).map(i => i.kebab);
  if (missing.length) {
    process.stderr.write(
      `[icons] ${missing.length} icon(s) without tags: ${missing.slice(0, 5).join(', ')}${missing.length > 5 ? '…' : ''}\n`
    );
  }

  const entries = icons
    .map(i => {
      const list = tags[i.kebab] ?? [];
      const arr = list.map(t => `'${t.replace(/'/g, "\\'")}'`).join(', ');
      // Quote keys only when they aren't valid identifiers (kebab-case needs quotes).
      const key = /^[A-Za-z_$][\w$]*$/.test(i.kebab) ? i.kebab : `'${i.kebab}'`;
      return `  ${key}: [${arr}],`;
    })
    .join('\n');

  const content = `${LICENSE}\n${AUTOGEN}/* eslint-disable */\n
import type { WrBuiltInIconName } from 'ngwr/icon';

/**
 * Search tags for the built-in icon set.
 *
 * Showcase-only — kept out of the published library so end-user bundles
 * don't pay for it. Source of truth: \`projects/lib/icon/_svg/_tags.json\`.
 */
export const iconTags: Record<WrBuiltInIconName, readonly string[]> = {
${entries}
};
`;

  mkdirSync(SHOWCASE_DATA_DIR, { recursive: true });
  writeFileSync(SHOWCASE_TAGS_FILE, content, 'utf-8');
}

function writeIconsIndex(icons: Icon[]): void {
  // Sort by camel name so the output matches `import-x/order` (alphabetical).
  const sorted = [...icons].sort((a, b) => a.camel.localeCompare(b.camel));

  const imports = sorted.map(i => `import { ${i.camel} } from './${i.kebab}';`).join('\n');
  const exports = sorted.map(i => `export { ${i.camel} } from './${i.kebab}';`).join('\n');
  const setMembers = sorted.map(i => `  ${i.camel},`).join('\n');

  const content =
    `${AUTOGEN}\n` +
    `import type { WrIcon } from '../types';\n\n` +
    `${imports}\n\n` +
    `${exports}\n\n` +
    `/**\n` +
    ` * Complete set of built-in icons.\n` +
    ` *\n` +
    ` * Importing this pulls every icon into the bundle — prefer importing\n` +
    ` * individual icons by name for tree-shaking. Use \`wrIconSet\` only for\n` +
    ` * icon pickers, documentation pages, or similar exhaustive listings.\n` +
    ` */\n` +
    `export const wrIconSet: WrIcon[] = [\n${setMembers}\n];\n`;

  writeFileSync(join(ICONS_DIR, 'index.ts'), content, 'utf-8');
}

// Run

rmSync(ICONS_DIR, { recursive: true, force: true });
mkdirSync(ICONS_DIR, { recursive: true });
mkdirSync(TYPES_DIR, { recursive: true });

const icons = collectIcons();
const tags = readTags();

writeIconNameType(icons);
for (const icon of icons) writeIconFile(icon);
writeIconsIndex(icons);
writeShowcaseTags(icons, tags);

process.stderr.write(`Generated ${icons.length} icons → ${ICONS_DIR}\n`);
process.stderr.write(`Generated tag map → ${SHOWCASE_TAGS_FILE}\n`);
